import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { validateGlb } from "../dist/packages/assets/src/index.js";
import { generateProxyBundle, parseProxyGeneratorInput, PROXY_REQUIRED_NODES } from "../dist/packages/frame-generation/src/index.js";
import { parseAssetManifest } from "../dist/packages/contracts/src/index.js";
import { evaluateAssetAdmission } from "../dist/packages/runtime/src/index.js";
import { loadVerifiedRuntimeAsset } from "../dist/apps/try-on-web/src/runtimeCatalog.js";

const fixtureUrl = new URL("../fixtures/frame-generation/proxy.synthetic.template.json", import.meta.url);
const digest = (bytes) => createHash("sha256").update(bytes).digest("hex");
async function fixture() { return JSON.parse(await readFile(fixtureUrl, "utf8")); }
function encoded(value) { return Buffer.from(`${JSON.stringify(value, null, 2)}\n`); }

test("canonical set-like sources produce byte-identical Proxy GLB and manifest", async () => {
  const firstInput = await fixture();
  const secondInput = structuredClone(firstInput);
  secondInput.sourceAssetHashes.reverse();
  const first = await generateProxyBundle(firstInput);
  const second = await generateProxyBundle(secondInput);
  assert.equal(first.canonicalInputSha256, second.canonicalInputSha256);
  assert.deepEqual(first.glb, second.glb);
  assert.equal(first.manifestJson, second.manifestJson);
  assert.equal(first.manifestSha256, second.manifestSha256);
});

test("a 1 mm measurement or profile point change changes canonical input and output hashes", async () => {
  const baseline = await generateProxyBundle(await fixture());
  const dimensionInput = await fixture(); dimensionInput.measurementSet.dimensionsMm.templeLength += 1;
  const dimension = await generateProxyBundle(dimensionInput);
  assert.notEqual(dimension.canonicalInputSha256, baseline.canonicalInputSha256);
  assert.notEqual(dimension.manifest.model.sha256, baseline.manifest.model.sha256);

  const profileInput = await fixture(); profileInput.profile.leftLens.inner[4][0] += 1;
  const profile = await generateProxyBundle(profileInput);
  assert.notEqual(profile.canonicalInputSha256, baseline.canonicalInputSha256);
  assert.notEqual(profile.manifest.model.sha256, baseline.manifest.model.sha256);
});

test("generated bytes pass the shared runtime GLB validator with metre actual bounds and required nodes", async () => {
  const input = await fixture();
  const bundle = await generateProxyBundle(input);
  const validated = validateGlb(bundle.glb, {
    requiredNodes: bundle.manifest.model.requiredNodes,
    unit: bundle.manifest.model.unit,
    expectedBoundsMetres: bundle.manifest.model.boundsMetres,
  });
  assert.deepEqual(bundle.manifest.model.requiredNodes, [...PROXY_REQUIRED_NODES]);
  assert.equal((validated.actualBoundsMetres.max[0] - validated.actualBoundsMetres.min[0]) * 1_000, 140.00000059604645);
  assert.ok(Math.abs(validated.actualBoundsMetres.min[2] * 1_000 + 145) < 0.001);
  assert.ok(validated.positionAccessorCount >= 4);
  assert.equal(parseAssetManifest(bundle.manifest).model.unit, "metre");
  const jsonLength = new DataView(bundle.glb.buffer, bundle.glb.byteOffset, bundle.glb.byteLength).getUint32(12, true);
  const binaryOffset = 20 + jsonLength + 8;
  const expectedFirstFloat = new Uint8Array(4);
  new DataView(expectedFirstFloat.buffer).setFloat32(0, input.profile.leftLens.outer[0][0] / 1_000, true);
  assert.deepEqual(bundle.glb.slice(binaryOffset, binaryOffset + 4), expectedFirstFloat, "POSITION floats must be serialized little-endian");
});

test("runtime catalog consumes generated manifest and exact GLB bytes without a generator-specific code path", async () => {
  const input = await fixture(); const bundle = await generateProxyBundle(input);
  const base = "https://catalog.example/generated/";
  const manifestUrl = `${base}${bundle.manifestFileName}`; const modelUrl = `${base}${bundle.glbFileName}`;
  const manifestBytes = Buffer.from(bundle.manifestJson);
  const asset = {
    id: input.candidate.assetId, tenantId: input.candidate.tenantId, frameModelId: input.candidate.frameModelId, version: 1,
    quality: "proxy", generationMethod: "proxy-auto", modelUrl: `./${bundle.glbFileName}`, manifestUrl: `./${bundle.manifestFileName}`,
    manifestSha256: digest(manifestBytes), sourceAssetHashes: [...bundle.manifest.sourceAssetHashes],
    attachmentMatrix: [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1], qualityEnvelope: { maxYawDeg: 0, maxPitchDeg: 0, recommendedForLive: false, scaleConfidence: "low" }, status: "draft",
  };
  const catalog = {
    schemaVersion: 1, tenantId: input.candidate.tenantId, defaultSku: "SYNTHETIC-PROXY",
    entries: [{ schemaVersion: 1, tenantId: input.candidate.tenantId,
      model: { id: input.candidate.frameModelId, tenantId: input.candidate.tenantId, modelCode: "SYNTHETIC", name: "Synthetic fixture", measurements: { lensWidthMm: 52, bridgeWidthMm: 18, templeLengthMm: 145, frameWidthMm: 140, lensHeightMm: 38, frameThicknessMm: 4 } },
      variant: { id: input.candidate.frameVariantId, tenantId: input.candidate.tenantId, frameModelId: input.candidate.frameModelId, sku: "SYNTHETIC-PROXY", frameColor: "synthetic orange", frameMaterial: "other", lensType: "clear" }, asset }],
  };
  const responses = new Map([[base + "catalog.json", encoded(catalog)], [manifestUrl, manifestBytes], [modelUrl, bundle.glb]]);
  const loaded = await loadVerifiedRuntimeAsset({ catalogUrl: base + "catalog.json", mode: "calibration", fetchFn: async (url) => new Response(responses.get(String(url)) ?? "missing", { status: responses.has(String(url)) ? 200 : 404 }) });
  assert.equal(loaded.verifiedGlb.sha256, bundle.manifest.model.sha256);
  assert.equal(loaded.manifest.fixture, true);
});

test("strict input rejects unknown, non-finite, out-of-range, hash, profile, and measurement failures", async () => {
  const cases = [];
  const unknown = await fixture(); unknown.status = "published"; cases.push([unknown, /status is not allowed/]);
  const nonFinite = await fixture(); nonFinite.measurementSet.dimensionsMm.frameWidth = NaN; cases.push([nonFinite, /finite number/]);
  const outOfRange = await fixture(); outOfRange.measurementSet.dimensionsMm.templeLength = 999; cases.push([outOfRange, /between 80 and 200/]);
  const sourceHash = await fixture(); sourceHash.sourceAssetHashes[0] = "bad"; cases.push([sourceHash, /SHA-256/]);
  const measurementHash = await fixture(); measurementHash.measurementSet.sha256 = "A".repeat(64); cases.push([measurementHash, /SHA-256/]);
  const winding = await fixture(); winding.profile.leftLens.outer.reverse(); cases.push([winding, /winding/]);
  const selfIntersection = await fixture(); selfIntersection.profile.leftLens.outer = [[-61,-19],[-9,19],[-9,-19],[-61,19]]; selfIntersection.profile.leftLens.inner = [[-55,-10],[-55,10],[-15,10],[-15,-10]]; cases.push([selfIntersection, /self-intersect/]);
  const holeEscape = await fixture(); holeEscape.profile.leftLens.inner[0] = [-80,-8]; cases.push([holeEscape, /strictly inside|intersect/]);
  const degenerate = await fixture(); degenerate.profile.leftLens.inner = [[-20,0],[-19,0],[-18,0],[-17,0],[-16,0],[-15,0],[-14,0],[-13,0]]; cases.push([degenerate, /degenerate|self-intersect/]);
  const inconsistent = await fixture(); inconsistent.measurementSet.dimensionsMm.lensWidth = 53; cases.push([inconsistent, /inconsistent/]);
  const rotatedHole = await fixture(); rotatedHole.profile.leftLens.inner.push(rotatedHole.profile.leftLens.inner.shift()); cases.push([rotatedHole, /point ordering|crossing rim connectors|connector crosses/]);
  for (const [candidate, pattern] of cases) assert.throws(() => parseProxyGeneratorInput(candidate), pattern);
});

test("Proxy authority fields are fixed and cannot be overridden into review, approval, preview, or live", async () => {
  const input = await fixture();
  for (const [key, value] of [["status", "published"], ["quality", "premium"], ["recommendedForLive", true]]) {
    const altered = structuredClone(input); altered[key] = value;
    assert.throws(() => parseProxyGeneratorInput(altered), /is not allowed/);
  }
  const bundle = await generateProxyBundle(input);
  assert.deepEqual({ status: bundle.manifest.proxyGeneration.status, quality: bundle.manifest.proxyGeneration.quality, recommendedForLive: bundle.manifest.proxyGeneration.recommendedForLive }, { status: "draft", quality: "proxy", recommendedForLive: false });
  const asset = { status: "draft", quality: "proxy", qualityEnvelope: { recommendedForLive: false } };
  assert.equal(evaluateAssetAdmission({ mode: "public-live", asset, fixture: true }).admitted, false);
  assert.equal(evaluateAssetAdmission({ mode: "qa-preview", asset, fixture: true }).admitted, false);
  assert.equal(bundle.manifest.proxyGeneration.g1, "active-not-ready");
  assert.equal(bundle.manifest.proxyGeneration.g2, "preparation-only-not-active-not-pass");
});
