import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

import { evaluateCaptureJigReadiness, evaluateRepresentativeCoverage, validateCaptureJigProfile, validateRepresentativeInventory } from "../dist/packages/contracts/src/index.js";
import { evaluateGenerationBakeoff, validateGenerationBakeoffEvidence } from "../dist/packages/quality/src/index.js";

const hash = (value) => createHash("sha256").update(value).digest("hex");
const CALIBRATION_BYTES = Buffer.from("physical calibration fixture bytes");
const load = async (name) => JSON.parse(await readFile(new URL(`../fixtures/g2/${name}`, import.meta.url), "utf8"));

async function selectedInventory() {
  const inventory = await load("representative-20.synthetic.json"); inventory.synthetic = false;
  inventory.candidates.forEach((candidate, index) => { candidate.selectionRationale.demand = "medium"; candidate.selectionRationale.continuity = "continuing"; candidate.rights = { status: "cleared", reference: `rights-${index}` }; candidate.readiness = { sources: "ready", measurements: "ready" }; candidate.immutableSources = [{ sourceAssetId: `source-${index}`, objectKey: `g2/model-${index}/front.png`, sha256: hash(`source-${index}`), byteLength: 1000 + index }]; });
  return inventory;
}

async function calibratedJig() {
  const jig = await load("capture-jig-v1.template.json"); const settings = hash("camera-settings"); jig.template = false; Object.assign(jig.camera, { settingsSha256: settings, distanceMm: 600, heightMm: 1200 }); jig.views.forEach((view) => { view.calibratedYawDeg = view.targetYawDeg; view.yawToleranceDeg = 1; }); Object.assign(jig.lighting, { illuminanceLux: 500, colorTemperatureK: 5500 }); jig.scaleMarker.certifiedLengthMm = 100; jig.caliper.calibrationReference = "caliper-certificate-1"; jig.angleGauge.calibrationReference = "gauge-certificate-1"; jig.calibrationArtifact = { objectKey: "calibration.bin", sha256: hash(CALIBRATION_BYTES), byteLength: CALIBRATION_BYTES.byteLength, verifiedAt: "2026-08-10T00:00:00Z", actorId: "operator-1" }; jig.operatorChecklist.forEach((item) => { item.complete = true; }); jig.replay = { runId: "capture-run-1", operatorId: "operator-1", capturedAt: "2026-08-10T01:00:00Z", cameraSettingsSha256: settings, protocolVersion: "g2-capture-v1" }; return jig;
}

function review(result = "approve") { return { reviewerId: "reviewer-1", result, recordedAt: "2026-08-10T04:00:00Z" }; }
function bakeoffRun(modelId, method, index) {
  const standard = method === "Standard"; const firstPass = standard && index < 10; const manual = standard && index >= 16;
  return { runId: `run-${method.replaceAll(" ", "-")}-${index}`, tenantId: "tenant-1", frameModelId: modelId, method, sourceAssetSha256s: [hash(`source-${modelId}`)], measurementSha256: hash(`measurement-${modelId}`), generator: { identity: `generator-${method}`, version: "1.0.0", configSha256: hash(`config-${method}`) }, inputSha256: hash(`input-${method}-${modelId}`), outputSha256: hash(`output-${method}-${modelId}`), artifactByteLength: 2000 + index, modelSha256: hash(`model-${method}-${modelId}`), modelByteLength: 1000 + index, angles: ["front", "15", "25"].map((angle) => ({ angle, renderSha256: hash(`render-${method}-${modelId}-${angle}`), artifactByteLength: 500, humanReview: review() })), sizeErrorPct: 2, materialReview: review(), visualReview: review(), performance: { deviceClass: "android-chrome-mid-range", runtimeVersion: "runtime-1", renderFps: 24, measuredAt: "2026-08-10T03:00:00Z", actorId: "performance-actor-1" }, correctionCount: firstPass ? 0 : 1, correctionMinutes: firstPass ? 0 : 8, approval: firstPass ? "approve" : manual ? "manual-model-required" : "approve-with-correction", firstPass, failureClassification: manual ? "manual-required" : "none", startedAt: "2026-08-10T00:00:00Z", completedAt: "2026-08-10T02:00:00Z", actorId: "operator-1" };
}
function bakeoff() { const modelIds = Array.from({ length: 20 }, (_, index) => `model-${index + 1}`); const premiumBaselineModelIds = modelIds.slice(0, 3); return { schemaVersion: 1, bakeoffId: "bakeoff-1", template: false, evaluatedAt: "2026-08-11T00:00:00Z", inventory: { inventoryId: "inventory-1", inventoryVersion: 1, inventorySha256: hash("inventory"), tenantId: "tenant-1", modelIds, premiumBaselineModelIds }, captureProfileSha256: hash("capture-profile"), runs: [...modelIds.flatMap((modelId, index) => ["Proxy", "Standard"].map((method) => bakeoffRun(modelId, method, index))), ...premiumBaselineModelIds.map((modelId, index) => bakeoffRun(modelId, "Premium", index))] }; }

test("synthetic representative 20 proves overlapping coverage without selection, rights, or capture claims", async () => { const input = await load("representative-20.synthetic.json"); const result = evaluateRepresentativeCoverage(input); assert.equal(result.documentValid, true); assert.equal(result.exactTwenty, true); assert.equal(result.representativenessPass, true); assert.equal(result.presentTraits.length, 9); assert.equal(result.commercialRationaleReady, false); assert.equal(result.rightsReady, false); assert.equal(result.captureReady, false); assert.equal(result.selectionReady, false); assert.equal(result.synthetic, true); });
test("selected representative inventory separates coverage from rights and capture readiness", async () => { const input = await selectedInventory(); assert.equal(evaluateRepresentativeCoverage(input).selectionReady, true); input.candidates[0].rights = { status: "pending", reference: null }; let result = evaluateRepresentativeCoverage(input); assert.equal(result.representativenessPass, true); assert.equal(result.rightsReady, false); assert.equal(result.captureReady, true); input.candidates[0].rights = { status: "cleared", reference: "rights-0" }; input.candidates[0].readiness.sources = "partial"; result = evaluateRepresentativeCoverage(input); assert.equal(result.rightsReady, true); assert.equal(result.captureReady, false); });
test("inventory rejects malformed unknown JSON, non-20 length, duplicate models, variants, and relabeled source hashes", async () => { const input = await selectedInventory(); input.unknown = true; input.candidates.pop(); input.candidates[1].frameModelId = input.candidates[0].frameModelId; input.candidates[1].representativeVariant.frameVariantId = input.candidates[0].representativeVariant.frameVariantId; input.candidates[1].immutableSources[0].sha256 = input.candidates[0].immutableSources[0].sha256; const paths = validateRepresentativeInventory(input).map((issue) => issue.path); for (const path of ["unknown", "candidates", "candidates.1.frameModelId", "candidates.1.representativeVariant.frameVariantId", "candidates.1.immutableSources.0.sha256"]) assert.ok(paths.includes(path), path); });
test("representative inventory rejects cross-tenant candidate relabeling", async () => { const input = await selectedInventory(); input.candidates[0].tenantId = "tenant-2"; assert.ok(validateRepresentativeInventory(input).some((issue) => issue.path === "candidates.0.tenantId" && issue.message.includes("inventory tenantId"))); });

test("committed jig template is spec-valid but fails physical calibration and run readiness", async () => { const result = evaluateCaptureJigReadiness(await load("capture-jig-v1.template.json")); assert.equal(result.specValid, true); assert.equal(result.physicallyCalibrated, false); assert.equal(result.runReady, false); assert.ok(result.calibrationBlockers.some((issue) => issue.path === "calibrationArtifact.sha256")); });
test("recorded calibration metadata alone cannot establish physical readiness", async () => { const result = evaluateCaptureJigReadiness(await calibratedJig()); assert.equal(result.calibrationArtifactVerified, false); assert.equal(result.physicallyCalibrated, false); assert.ok(result.calibrationBlockers.some((issue) => issue.path === "calibrationArtifact")); });
test("independently inspected calibration hash and bytes can establish run readiness", async () => { const result = evaluateCaptureJigReadiness(await calibratedJig(), { sha256: hash(CALIBRATION_BYTES), byteLength: CALIBRATION_BYTES.byteLength }); assert.deepEqual(result.specificationIssues, []); assert.deepEqual(result.calibrationBlockers, []); assert.deepEqual(result.runBlockers, []); assert.equal(result.calibrationArtifactVerified, true); assert.equal(result.runReady, true); });
test("capture run cannot predate the verified calibration artifact", async () => { const jig = await calibratedJig(); jig.replay.capturedAt = "2026-08-09T23:59:59Z"; const result = evaluateCaptureJigReadiness(jig, { sha256: hash(CALIBRATION_BYTES), byteLength: CALIBRATION_BYTES.byteLength }); assert.equal(result.runReady, false); assert.ok(result.runBlockers.some((issue) => issue.path === "replay.capturedAt")); });
test("jig validator rejects unknown fields, bad role targets, duplicate roles and invalid artifact bytes/hash", async () => { const input = await calibratedJig(); input.extra = true; input.views[1].targetYawDeg = 15; input.views[2].role = "left15"; input.calibrationArtifact.sha256 = "bad"; input.calibrationArtifact.byteLength = 0; const paths = validateCaptureJigProfile(input).map((issue) => issue.path); for (const path of ["extra", "views.1.targetYawDeg", "views.2.role", "calibrationArtifact.sha256", "calibrationArtifact.byteLength"]) assert.ok(paths.includes(path), path); });

test("complete 43-cell internal bakeoff passes without optional Commercial Reference", () => { const result = evaluateGenerationBakeoff(bakeoff()); assert.equal(result.documentValidity.valid, true); assert.equal(result.evidenceCompleteness.complete, true); assert.equal(result.evidenceCompleteness.requiredCells, 43); assert.equal(result.evidenceCompleteness.commercialReferencePresent, false); assert.equal(result.metrics.autoFirstPassApprovalPct, 50); assert.equal(result.metrics.standardCorrectionMedianMinutes, 4); assert.equal(result.metrics.manualModelSharePct, 20); assert.equal(result.metrics.pass, true); assert.equal(result.stopSignals.triggered, false); assert.equal(result.strategySelectionReadiness, true); });
test("Premium baselines require exactly 3 distinct inventory models and reject extra Premium cells", () => { let input = bakeoff(); input.inventory.premiumBaselineModelIds.pop(); let codes = validateGenerationBakeoffEvidence(input).map((issue) => issue.code); assert.ok(codes.includes("invalid_premium_baseline_count")); input = bakeoff(); input.runs.push(bakeoffRun("model-4", "Premium", 44)); codes = validateGenerationBakeoffEvidence(input).map((issue) => issue.code); assert.ok(codes.includes("unexpected_premium_run")); });
test("bakeoff rejects unknown JSON, duplicate cells and relabeled artifacts", () => { const input = bakeoff(); input.unknown = true; input.runs.push(structuredClone(input.runs[0])); input.runs.at(-1).runId = "duplicate-cell"; input.runs[1].modelSha256 = input.runs[0].modelSha256; const codes = validateGenerationBakeoffEvidence(input).map((issue) => issue.code); for (const code of ["unknown_field", "duplicate_cell", "reused_artifact"]) assert.ok(codes.includes(code), code); });
test("bakeoff tenant binding rejects relabeled runs", () => { const input = bakeoff(); input.runs[0].tenantId = "tenant-2"; assert.ok(validateGenerationBakeoffEvidence(input).some((issue) => issue.code === "tenant_mismatch")); });
test("required comparison cells bind the same canonical sources and measurement", () => { const input = bakeoff(); const standard = input.runs.find((run) => run.frameModelId === "model-1" && run.method === "Standard"); standard.sourceAssetSha256s = [hash("substituted-source")]; standard.measurementSha256 = hash("substituted-measurement"); const codes = validateGenerationBakeoffEvidence(input).map((issue) => issue.code); assert.ok(codes.includes("comparison_source_mismatch")); assert.ok(codes.includes("comparison_measurement_mismatch")); });
test("input and render bytes cannot be relabeled across cells", () => { const input = bakeoff(); input.runs[1].inputSha256 = input.runs[0].inputSha256; input.runs[1].angles[0].renderSha256 = input.runs[0].angles[0].renderSha256; const reused = validateGenerationBakeoffEvidence(input).filter((issue) => issue.code === "reused_artifact"); assert.ok(reused.some((issue) => issue.path.endsWith("inputSha256"))); assert.ok(reused.some((issue) => issue.path.endsWith("renderSha256"))); });
test("front, 15, and 25 degree evidence cannot reuse one render artifact", () => { const input = bakeoff(); input.runs[0].angles[1].renderSha256 = input.runs[0].angles[0].renderSha256; assert.ok(validateGenerationBakeoffEvidence(input).some((issue) => issue.code === "reused_artifact" && issue.path === "runs.0.angles.1.renderSha256")); });
test("human reviews must be post-run and no later than evaluatedAt", () => { const input = bakeoff(); input.runs[0].angles[0].humanReview.recordedAt = "2026-08-12T00:00:00Z"; input.runs[0].materialReview.recordedAt = "2026-08-10T01:00:00Z"; const issues = validateGenerationBakeoffEvidence(input); assert.ok(issues.some((issue) => issue.code === "future_evidence" && issue.path.includes("humanReview.recordedAt"))); assert.ok(issues.some((issue) => issue.code === "review_before_completion" && issue.path.includes("materialReview.recordedAt"))); });
test("desktop-only performance is invalid and cannot select a strategy", () => { const input = bakeoff(); input.runs[0].performance.deviceClass = "windows-chrome"; const result = evaluateGenerationBakeoff(input); assert.equal(result.documentValidity.valid, false); assert.equal(result.strategySelectionReadiness, false); assert.ok(result.documentValidity.issues.some((issue) => issue.path === "runs.0.performance.deviceClass")); });
test("missing per-angle human review and device performance fail document and evidence completeness", () => { const input = bakeoff(); delete input.runs[0].angles[0].humanReview; delete input.runs[1].performance.renderFps; const result = evaluateGenerationBakeoff(input); assert.equal(result.documentValidity.valid, false); assert.equal(result.evidenceCompleteness.complete, false); assert.equal(result.metrics.defined, false); assert.equal(result.strategySelectionReadiness, false); });
test("metric boundaries use >=50 first pass, <=10 median, and <=25 manual share", () => { let input = bakeoff(); input.runs.filter((run) => run.method === "Standard" && !run.firstPass).forEach((run) => { run.correctionMinutes = 20; }); let result = evaluateGenerationBakeoff(input); assert.equal(result.metrics.standardCorrectionMedianMinutes, 10); assert.equal(result.metrics.pass, true); input = bakeoff(); input.runs.filter((run) => run.method === "Standard").slice(15).forEach((run) => { run.approval = "manual-model-required"; run.failureClassification = "manual-required"; }); result = evaluateGenerationBakeoff(input); assert.equal(result.metrics.manualModelSharePct, 25); assert.equal(result.metrics.pass, true); assert.equal(result.stopSignals.manualShareOver25, false); });
test("stop signals remain distinct at strict >15, >25 and mobile <20 boundaries", () => { let input = bakeoff(); const standard = input.runs.find((run) => run.method === "Standard" && !run.firstPass); standard.correctionMinutes = 15; standard.performance.renderFps = 20; let result = evaluateGenerationBakeoff(input); assert.deepEqual(result.stopSignals.standardCorrectionOver15, []); assert.deepEqual(result.stopSignals.mobileUnder20Fps, []); standard.correctionMinutes = 15.01; standard.performance.renderFps = 19.99; result = evaluateGenerationBakeoff(input); assert.ok(result.stopSignals.standardCorrectionOver15.includes(standard.runId)); assert.ok(result.stopSignals.mobileUnder20Fps.includes(standard.runId)); input.runs.filter((run) => run.method === "Standard").slice(14).forEach((run) => { run.approval = "manual-model-required"; run.failureClassification = "manual-required"; }); result = evaluateGenerationBakeoff(input); assert.equal(result.stopSignals.manualShareOver25, true); assert.equal(result.strategySelectionReadiness, false); });
test("committed G2 CLIs fail closed with structured reports", () => { for (const [cli, fixture, key] of [["g2-inventory-cli.mjs", "representative-20.synthetic.json", "selectionReady"], ["g2-jig-cli.mjs", "capture-jig-v1.template.json", "runReady"], ["g2-bakeoff-cli.mjs", "bakeoff.template.json", "strategySelectionReadiness"]]) { const run = spawnSync(process.execPath, [`apps/quality-harness/${cli}`, `fixtures/g2/${fixture}`], { encoding: "utf8" }); assert.equal(run.status, 1, run.stderr); assert.equal(JSON.parse(run.stdout)[key], false); } });
test("jig CLI independently inspects safe relative calibration artifact bytes", async () => { const directory = await mkdtemp(join(tmpdir(), "jessica-g2-jig-")); const profilePath = join(directory, "profile.json"); await writeFile(join(directory, "calibration.bin"), CALIBRATION_BYTES); await writeFile(profilePath, JSON.stringify(await calibratedJig())); const run = spawnSync(process.execPath, ["apps/quality-harness/g2-jig-cli.mjs", profilePath, "calibration.bin"], { encoding: "utf8" }); assert.equal(run.status, 0, run.stdout); const result = JSON.parse(run.stdout); assert.equal(result.calibrationArtifactVerified, true); assert.equal(result.runReady, true); });
test("jig CLI rejects unsafe artifact paths without leaking private paths", async () => { const directory = await mkdtemp(join(tmpdir(), "jessica-g2-jig-unsafe-")); const profilePath = join(directory, "profile.json"); await writeFile(profilePath, JSON.stringify(await calibratedJig())); const run = spawnSync(process.execPath, ["apps/quality-harness/g2-jig-cli.mjs", profilePath, "../private-calibration.bin"], { encoding: "utf8" }); assert.equal(run.status, 2); assert.equal(run.stderr, ""); assert.equal(JSON.parse(run.stdout).error.code, "unsafe_artifact_path"); assert.equal(run.stdout.includes(directory), false); assert.equal(run.stdout.includes(profilePath), false); });
test("all G2 CLIs sanitize malformed and missing input errors", async () => { const directory = await mkdtemp(join(tmpdir(), "jessica-g2-errors-")); const malformed = join(directory, "private-malformed.json"); const missing = join(directory, "private-missing.json"); await writeFile(malformed, "{ secret malformed"); for (const cli of ["g2-inventory-cli.mjs", "g2-jig-cli.mjs", "g2-bakeoff-cli.mjs"]) for (const [path, code] of [[malformed, "invalid_json"], [missing, "input_unavailable"]]) { const run = spawnSync(process.execPath, [`apps/quality-harness/${cli}`, path], { encoding: "utf8" }); assert.equal(run.status, 2); assert.equal(run.stderr, ""); assert.equal(JSON.parse(run.stdout).error.code, code); assert.equal(run.stdout.includes(directory), false); assert.equal(run.stdout.includes(path), false); } });
