import test from "node:test";
import assert from "node:assert/strict";
import {
  REPROCESSING_AUTHORITY_DENIALS, REPROCESSING_COMPARISONS, REPROCESSING_DECISIONS,
  REPROCESSING_EVENT_TYPES, REPROCESSING_METRICS, REPROCESSING_REASONS, REPROCESSING_TRIGGERS,
  bindReprocessingEvent, bindReprocessingRequest, canonicalJson, parseReprocessingEvent,
} from "../dist/packages/contracts/src/index.js";
import {
  appendReprocessingEvent, buildReprocessingCommand, createReprocessingRequestedEvent,
  replayReprocessingLedger, verifyReprocessingCommand,
} from "../dist/packages/reprocessing/src/index.js";

const BASE = "2026-08-11T12:00:00.000Z";
const at = (seconds) => new Date(Date.parse(BASE) + seconds * 1_000).toISOString();
const digest = (character) => character.repeat(64);
function version(version = 1, suffix = "old", overrides = {}) {
  return { assetId: "asset-a", assetVersion: version, manifestSha256: digest(version === 1 ? "1" : "a"), modelSha256: digest(version === 1 ? "2" : "b"), generationJobId: `job-${suffix}`, generationCanonicalInputSha256: digest(version === 1 ? "3" : "c"), generationInputSha256: digest(version === 1 ? "4" : "d"), generationHeadEventSha256: digest(version === 1 ? "5" : "e"), reviewHeadEvidenceSha256: digest(version === 1 ? "6" : "f"), qaCandidateSha256: digest(version === 1 ? "7" : "8"), referenceStatus: "digest-candidate-unverified", ...overrides };
}
async function request(overrides = {}) {
  const next = version(2, "new");
  return bindReprocessingRequest({ schemaVersion: 1, type: "reprocessing.request", createdAt: BASE, trigger: "qa-correction", reason: "QA_DEFECT", binding: { tenantId: "tenant-a", siteId: "site-a", environment: "production", sku: "sku-a", frameModelId: "model-a", frameVariantId: "variant-a", previous: version(), sourceCandidateSha256: digest("9"), captureCandidateSha256: digest("a"), provenanceStatus: "candidate-references-unverified" }, newGenerationRequestId: next.generationJobId, newGenerationCanonicalInputSha256: next.generationCanonicalInputSha256, newGenerationInputSha256: next.generationInputSha256, maxAttempts: 1, rawMaterialStatus: "digest-references-only-unverified", rawMaterialAuthority: false, policyVersion: "f4-local-v1", ...overrides });
}
async function baseLedger() { const req = await request(); const genesis = await createReprocessingRequestedEvent(req); const initial = await replayReprocessingLedger([genesis], BASE); const candidate = await appendReprocessingEvent(initial, "candidate-1", "candidate-referenced", at(1), { attempt: 1, candidate: version(2, "new") }); return { req, genesis, candidate, candidatePlan: await replayReprocessingLedger([genesis, candidate], at(1)) }; }
function metrics(values = [[100, 90], [200, 180], [300, 300]]) { return REPROCESSING_METRICS.map((metric, index) => ({ metric, previousValue: values[index][0], candidateValue: values[index][1], evidenceCandidateSha256: digest(String(index + 1)), evidenceStatus: "metric-candidate-unverified" })); }
async function withComparison(metricEvidence = metrics()) { const base = await baseLedger(); const comparison = await appendReprocessingEvent(base.candidatePlan, "comparison-1", "comparison-recorded", at(2), { metrics: metricEvidence }); return { ...base, comparison, comparisonPlan: await replayReprocessingLedger([base.genesis, base.candidate, comparison], at(2)) }; }

test("request and ledger bind old/new identities while raw material and every authority remain false", async () => {
  const state = await withComparison(); assert.equal(state.comparisonPlan.comparison, "better"); assert.equal(state.req.rawMaterialAuthority, false); assert.equal(state.req.rawMaterialStatus, "digest-references-only-unverified"); assert.notEqual(state.comparisonPlan.request.binding.previous.generationJobId, state.comparisonPlan.candidate.generationJobId);
  const serialized = canonicalJson(state.comparisonPlan); for (const forbidden of ["localraw:", "https://", "filePath", "rawBytes", "media", "recommendedForLive\":true", "qaApproved\":true"]) assert.equal(serialized.includes(forbidden), false);
});

test("request identity deterministically derives from an identity-free projection and rejects tampering", async () => { const first=await request(); const second=await request(); assert.deepEqual(first,second); assert.equal(first.requestId,`rp_${first.requestSha256}`); assert.equal(first.idempotencyKey,`rpv1_${first.requestSha256}`); const changed=structuredClone(first); changed.binding.sku="sku-tampered"; await assert.rejects(createReprocessingRequestedEvent(changed),/digest or identity/); const relabel=structuredClone(first); relabel.requestId=`rp_${digest("b")}`; await assert.rejects(createReprocessingRequestedEvent(relabel),/digest or identity/); });

test("each ledger prefix reports its exact preparation state", async () => { const base=await baseLedger(); assert.equal((await replayReprocessingLedger([base.genesis],BASE)).decision,"awaiting-candidate"); assert.equal(base.candidatePlan.decision,"awaiting-comparison"); const compared=await withComparison(); assert.equal(compared.comparisonPlan.decision,"canary-planning-required"); });

test("closed allowlists are runtime frozen", () => { for (const list of [REPROCESSING_TRIGGERS, REPROCESSING_REASONS, REPROCESSING_EVENT_TYPES, REPROCESSING_METRICS, REPROCESSING_COMPARISONS, REPROCESSING_DECISIONS]) { assert.equal(Object.isFrozen(list), true); assert.throws(() => list.push("invented"), TypeError); } });

test("comparison requires complete closed metric evidence for better or equivalent", async () => {
  assert.equal((await withComparison(metrics())).comparisonPlan.comparison, "better"); assert.equal((await withComparison(metrics([[1,1],[2,2],[3,3]]))).comparisonPlan.comparison, "equivalent"); assert.equal((await withComparison(metrics([[1,0],[2,3],[3,2]]))).comparisonPlan.comparison, "worse");
  const absent = await withComparison([]); assert.equal(absent.comparisonPlan.comparison, "manual-required"); assert.equal(absent.comparisonPlan.decision, "manual-required");
  const partial = await withComparison(metrics().slice(0, 2)); assert.equal(partial.comparisonPlan.comparison, "manual-required");
});

test("canary is bounded to one exact SKU, partial traffic, finite duration, and later authority", async () => {
  const state = await withComparison(); const canary = await appendReprocessingEvent(state.comparisonPlan, "canary-1", "canary-planned", at(3), { trafficBasisPoints: 500, durationMinutes: 60, skuScope: ["sku-a"], humanAuthorityRequired: true, controlPlaneAuthorityRequired: true }); const plan = await replayReprocessingLedger([state.genesis, state.candidate, state.comparison, canary], at(3)); assert.equal(plan.decision, "canary-candidate"); assert.equal(plan.authority.publication, false); assert.equal(plan.operationalStatus, "local-preparation-only"); assert.equal(plan.g5Ready, false);
  for (const payload of [{ trafficBasisPoints: 10_000, durationMinutes: 60, skuScope: ["sku-a"], humanAuthorityRequired: true, controlPlaneAuthorityRequired: true }, { trafficBasisPoints: 1, durationMinutes: 1, skuScope: ["*"], humanAuthorityRequired: true, controlPlaneAuthorityRequired: true }, { trafficBasisPoints: 1, durationMinutes: 1, skuScope: ["sku-a"], humanAuthorityRequired: false, controlPlaneAuthorityRequired: true }]) await assert.rejects(appendReprocessingEvent(state.comparisonPlan, "bad-canary", "canary-planned", at(3), payload), /bounded|identifier|authority/);
});

test("rollback targets only the exactly referenced older version and is never automatic", async () => {
  const state = await withComparison(metrics([[1,2],[2,3],[3,4]])); const payload = { target: state.req.binding.previous, humanAuthorityRequired: true, controlPlaneAuthorityRequired: true, automaticRollback: false }; const rollback = await appendReprocessingEvent(state.comparisonPlan, "rollback-1", "rollback-planned", at(3), payload); const plan = await replayReprocessingLedger([state.genesis, state.candidate, state.comparison, rollback], at(3)); assert.equal(plan.decision, "rollback-reference-manual-required"); assert.equal(plan.rollback.target.referenceStatus,"digest-candidate-unverified"); assert.equal(plan.authority.automaticRollback, false);
  for (const target of [version(2, "new"), version(1, "unknown", { manifestSha256: digest("b") }), version(3, "future")]) { const event = await appendReprocessingEvent(state.comparisonPlan, `rollback-${target.generationJobId}`, "rollback-planned", at(3), { ...payload, target }); await assert.rejects(replayReprocessingLedger([state.genesis, state.candidate, state.comparison, event], at(3)), /exactly referenced|roll forward/); }
  await assert.rejects(appendReprocessingEvent(state.comparisonPlan, "auto", "rollback-planned", at(3), { ...payload, automaticRollback: true }), /manually authorized/);
  for (const good of [metrics(), metrics([[1,1],[2,2],[3,3]])]) { const nonWorse=await withComparison(good); const event=await appendReprocessingEvent(nonWorse.comparisonPlan,"wrong-branch","rollback-planned",at(3),payload); await assert.rejects(replayReprocessingLedger([nonWorse.genesis,nonWorse.candidate,nonWorse.comparison,event],at(3)),/worse or manual-required/); }
});

test("candidate cannot duplicate, roll backward, or substitute asset/generation identities", async () => {
  const req = await request(); const genesis = await createReprocessingRequestedEvent(req); const initial = await replayReprocessingLedger([genesis], BASE);
  for (const candidate of [version(), version(2, "new", { assetId: "other" }), version(2, "other"), version(0, "new")]) await assert.rejects(async () => { const event = await appendReprocessingEvent(initial, `candidate-${candidate.assetId}-${candidate.assetVersion}-${candidate.generationJobId}`, "candidate-referenced", at(1), { attempt: 1, candidate }); await replayReprocessingLedger([genesis, event], at(1)); }, /advance|asset identity|generation request|bounded/);
});

test("hash chain rejects redigest, replay, reorder, future, stale, and post-terminal escalation", async () => {
  const state = await withComparison(); const changed = structuredClone(state.candidate); changed.payload.candidate.modelSha256 = digest("1"); await assert.rejects(replayReprocessingLedger([state.genesis, changed], at(2)), /digest/); await assert.rejects(replayReprocessingLedger([state.genesis, state.candidate, state.candidate], at(2)), /duplicated|sequence/); await assert.rejects(replayReprocessingLedger([state.genesis, state.comparison, state.candidate], at(2)), /chain|reordered/); await assert.rejects(replayReprocessingLedger([state.genesis, state.candidate], BASE), /future/); await assert.rejects(replayReprocessingLedger([state.genesis, state.candidate], at(86_402)), /stale/);
  const canary = await appendReprocessingEvent(state.comparisonPlan, "canary-terminal", "canary-planned", at(3), { trafficBasisPoints: 1, durationMinutes: 1, skuScope: ["sku-a"], humanAuthorityRequired: true, controlPlaneAuthorityRequired: true }); const canaryPlan = await replayReprocessingLedger([state.genesis, state.candidate, state.comparison, canary], at(3)); const after = await appendReprocessingEvent(canaryPlan, "after-terminal", "rollback-planned", at(4), { target: state.req.binding.previous, humanAuthorityRequired: true, controlPlaneAuthorityRequired: true, automaticRollback: false }); await assert.rejects(replayReprocessingLedger([state.genesis, state.candidate, state.comparison, canary, after], at(4)), /terminal/);
});

test("canonical commands are deterministic, idempotent, independently replayed, and authority denying", async () => {
  const state = await withComparison(); const first = await buildReprocessingCommand([state.genesis, state.candidate, state.comparison], at(2)); const second = await buildReprocessingCommand([state.genesis, state.candidate, state.comparison], at(2)); assert.deepEqual(first, second); assert.deepEqual(first.authority, REPROCESSING_AUTHORITY_DENIALS); assert.equal(Object.isFrozen(first), true); assert.deepEqual(await verifyReprocessingCommand(first), first);
  const escalation = structuredClone(first); escalation.decision = "canary-candidate"; await assert.rejects(verifyReprocessingCommand(await redigest(escalation)), /inconsistent/); const authority = structuredClone(first); authority.authority.publication = true; await assert.rejects(verifyReprocessingCommand(await redigest(authority)), /authority/); const ledger=structuredClone(first); ledger.ledger[1].payload.candidate.modelSha256=digest("1"); await assert.rejects(verifyReprocessingCommand(await redigest(ledger)),/digest/); const status=structuredClone(first); status.operationalStatus="production-ready"; await assert.rejects(verifyReprocessingCommand(await redigest(status)),/inconsistent/); const stale=structuredClone(first); stale.evaluatedAt=at(86_403); await assert.rejects(verifyReprocessingCommand(await redigest(stale)),/stale/);
});

async function redigest(command) { const copy = structuredClone(command); const zero = "0".repeat(64); let length = copy.byteLength; for (let i=0;i<8;i+=1) { const projected = { ...copy, byteLength:length, commandSha256:zero, commandIdempotencyKey:`rpcv1_${zero}` }; const next = new TextEncoder().encode(canonicalJson(projected)).byteLength; if (next===length) break; length=next; } const projected = { ...copy, byteLength:length, commandSha256:zero, commandIdempotencyKey:`rpcv1_${zero}` }; const { sha256Hex } = await import("../dist/packages/contracts/src/index.js"); const hash = await sha256Hex(canonicalJson(projected)); return { ...copy, byteLength:length, commandSha256:hash, commandIdempotencyKey:`rpcv1_${hash}` }; }

test("unknown/prototype/accessor/symbol/cycle/sparse/oversize and async TOCTOU inputs fail closed", async () => {
  const req = await request(); assert.throws(() => parseReprocessingEvent({ unknown: true }), /fields|version/); await assert.rejects(request({ newGenerationRequestId:"localraw:secret" }),/non-resource/); const proto = Object.assign(Object.create({}), req); await assert.rejects(createReprocessingRequestedEvent(proto), /plain/); let touched=false; const accessor={...req}; Object.defineProperty(accessor,"binding",{enumerable:true,get(){touched=true;return req.binding;}}); await assert.rejects(createReprocessingRequestedEvent(accessor), /data properties/); assert.equal(touched,false); const symbol={...req}; symbol[Symbol("x")]=1; await assert.rejects(createReprocessingRequestedEvent(symbol), /symbols/); const cycle={...req}; cycle.binding=cycle; await assert.rejects(createReprocessingRequestedEvent(cycle), /acyclic/); const sparse=[]; sparse.length=1; await assert.rejects(replayReprocessingLedger(sparse,BASE), /dense/); await assert.rejects(replayReprocessingLedger([await createReprocessingRequestedEvent(req)],"2026-02-31T00:00:00.000Z"),/real canonical/); const state=await withComparison(); const hostile=structuredClone(state.candidate); Object.defineProperty(hostile.payload,"candidate",{enumerable:true,get(){touched=true;return version(2,"new");}}); await assert.rejects(replayReprocessingLedger([state.genesis,hostile],at(2)),/data properties/); assert.equal(touched,false); const mutable=structuredClone(await buildReprocessingCommand([state.genesis,state.candidate,state.comparison],at(2))); const pending=verifyReprocessingCommand(mutable); mutable.decision="canary-candidate"; mutable.ledger[1].payload.candidate.assetId="mutated"; assert.equal((await pending).decision,"canary-planning-required");
});

test("request binding and ledger replay snapshot before their first asynchronous digest", async () => { const next=version(2,"new"); const mutable={ schemaVersion:1,type:"reprocessing.request",createdAt:BASE,trigger:"qa-correction",reason:"QA_DEFECT",binding:{tenantId:"tenant-a",siteId:"site-a",environment:"production",sku:"sku-original",frameModelId:"model-a",frameVariantId:"variant-a",previous:version(),sourceCandidateSha256:digest("9"),captureCandidateSha256:digest("a"),provenanceStatus:"candidate-references-unverified"},newGenerationRequestId:next.generationJobId,newGenerationCanonicalInputSha256:next.generationCanonicalInputSha256,newGenerationInputSha256:next.generationInputSha256,maxAttempts:1,rawMaterialStatus:"digest-references-only-unverified",rawMaterialAuthority:false,policyVersion:"f4-local-v1"}; const pendingRequest=bindReprocessingRequest(mutable); mutable.binding.sku="sku-mutated"; const bound=await pendingRequest; assert.equal(bound.binding.sku,"sku-original"); const genesis=await createReprocessingRequestedEvent(bound); const plan=await replayReprocessingLedger([genesis],BASE); const event=await appendReprocessingEvent(plan,"snapshot-event","candidate-referenced",at(1),{attempt:1,candidate:next}); const ledger=structuredClone([genesis,event]); const pendingReplay=replayReprocessingLedger(ledger,at(1)); ledger[1].payload.candidate.assetId="mutated"; ledger[1].eventSha256=digest("0"); const replayed=await pendingReplay; assert.equal(replayed.candidate.assetId,"asset-a"); });
