import { BAKEOFF_ANGLES, BAKEOFF_METHODS, BAKEOFF_MOBILE_DEVICE_CLASSES, REQUIRED_BAKEOFF_METHODS, type BakeoffIssue } from "../../contracts/src/generationBakeoff.js";
export type GenerationBakeoffEvaluation = {
  documentValidity: { valid: boolean; issues: BakeoffIssue[] };
  evidenceCompleteness: { complete: boolean; requiredCells: number; presentCells: number; missingCells: string[]; duplicateCells: string[]; issues: BakeoffIssue[]; commercialReferencePresent: boolean };
  metrics: { defined: boolean; autoFirstPassApprovalPct: number | null; standardCorrectionMedianMinutes: number | null; manualModelSharePct: number | null; pass: boolean };
  stopSignals: { triggered: boolean; standardCorrectionOver15: string[]; manualShareOver25: boolean; mobileUnder20Fps: string[] };
  strategySelectionReadiness: boolean;
  template: boolean | null;
};

const HASH = /^[a-f0-9]{64}$/; const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const ROOT_KEYS = ["schemaVersion", "bakeoffId", "template", "evaluatedAt", "inventory", "captureProfileSha256", "runs"] as const;
const INVENTORY_KEYS = ["inventoryId", "inventoryVersion", "inventorySha256", "tenantId", "modelIds", "premiumBaselineModelIds"] as const;
const RUN_KEYS = ["runId", "tenantId", "frameModelId", "method", "sourceAssetSha256s", "measurementSha256", "generator", "inputSha256", "outputSha256", "artifactByteLength", "modelSha256", "modelByteLength", "angles", "sizeErrorPct", "materialReview", "visualReview", "performance", "correctionCount", "correctionMinutes", "approval", "firstPass", "failureClassification", "startedAt", "completedAt", "actorId"] as const;
const GENERATOR_KEYS = ["identity", "version", "configSha256"] as const; const ANGLE_KEYS = ["angle", "renderSha256", "artifactByteLength", "humanReview"] as const;
const REVIEW_KEYS = ["reviewerId", "result", "recordedAt"] as const; const PERFORMANCE_KEYS = ["deviceClass", "runtimeVersion", "renderFps", "measuredAt", "actorId"] as const;
const APPROVALS = ["approve", "approve-with-correction", "manual-model-required", "reject"] as const;
const REVIEW_RESULTS = ["approve", "correction-required", "manual-model-required", "reject"] as const;
const FAILURES = ["none", "generation-failed", "geometry", "material", "size", "performance", "manual-required", "unsupported"] as const;

class Validator {
  readonly issues: BakeoffIssue[] = [];
  issue(code: string, path: string, message: string): void { this.issues.push({ code, path, message }); }
  object(value: unknown, path: string, keys: readonly string[]): Record<string, unknown> | null { if (typeof value !== "object" || value === null || Array.isArray(value)) { this.issue("invalid_type", path, "must be an object"); return null; } const result = value as Record<string, unknown>; for (const key of Object.keys(result)) if (!keys.includes(key)) this.issue("unknown_field", `${path}${path ? "." : ""}${key}`, "field is not allowed"); return result; }
  array(value: unknown, path: string): unknown[] { if (!Array.isArray(value)) { this.issue("invalid_type", path, "must be an array"); return []; } return value; }
  text(value: unknown, path: string): string { if (typeof value !== "string" || !value.trim()) { this.issue("invalid_string", path, "must be a non-blank pseudonymous identifier or value"); return ""; } return value; }
  hash(value: unknown, path: string): string { const result = this.text(value, path); if (!HASH.test(result)) this.issue("invalid_hash", path, "must be a lowercase SHA-256 digest"); return result; }
  date(value: unknown, path: string): string { const result = this.text(value, path); if (!ISO.test(result) || Number.isNaN(Date.parse(result))) this.issue("invalid_timestamp", path, "must be an ISO-8601 UTC timestamp"); return result; }
  number(value: unknown, path: string, integer = false, positive = false): number { if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || (integer && !Number.isInteger(value)) || (positive && value === 0)) { this.issue("invalid_number", path, `must be a ${positive ? "positive" : "non-negative"} finite${integer ? " integer" : " number"}`); return 0; } return value; }
  boolean(value: unknown, path: string): boolean { if (typeof value !== "boolean") { this.issue("invalid_boolean", path, "must be boolean"); return false; } return value; }
  enum<T extends string>(value: unknown, path: string, values: readonly T[]): T { const result = this.text(value, path); if (!values.includes(result as T)) { this.issue("invalid_enum", path, `must be one of: ${values.join(", ")}`); return values[0]!; } return result as T; }
}

function review(v: Validator, value: unknown, path: string): string { const r = v.object(value, path, REVIEW_KEYS); v.text(r?.reviewerId, `${path}.reviewerId`); v.enum(r?.result, `${path}.result`, REVIEW_RESULTS); return v.date(r?.recordedAt, `${path}.recordedAt`); }

export function validateGenerationBakeoffEvidence(input: unknown): BakeoffIssue[] {
  const v = new Validator(); const root = v.object(input, "", ROOT_KEYS); if (!root) return v.issues;
  if (root.schemaVersion !== 1) v.issue("invalid_version", "schemaVersion", "must equal 1"); v.text(root.bakeoffId, "bakeoffId"); v.boolean(root.template, "template"); const evaluatedAt = v.date(root.evaluatedAt, "evaluatedAt"); v.hash(root.captureProfileSha256, "captureProfileSha256");
  const inventory = v.object(root.inventory, "inventory", INVENTORY_KEYS); v.text(inventory?.inventoryId, "inventory.inventoryId"); v.number(inventory?.inventoryVersion, "inventory.inventoryVersion", true, true); v.hash(inventory?.inventorySha256, "inventory.inventorySha256"); const tenantId = v.text(inventory?.tenantId, "inventory.tenantId");
  const modelIds = v.array(inventory?.modelIds, "inventory.modelIds"); if (modelIds.length !== 20) v.issue("invalid_inventory_count", "inventory.modelIds", "must contain exactly 20 FrameModel ids"); const modelSet = new Set<string>(); modelIds.forEach((id, index) => { const parsed = v.text(id, `inventory.modelIds.${index}`); if (modelSet.has(parsed)) v.issue("duplicate_model", `inventory.modelIds.${index}`, "must be unique"); modelSet.add(parsed); });
  const premiumIds = v.array(inventory?.premiumBaselineModelIds, "inventory.premiumBaselineModelIds"); if (premiumIds.length !== 3) v.issue("invalid_premium_baseline_count", "inventory.premiumBaselineModelIds", "must contain exactly 3 distinct difficult FrameModel ids"); const premiumSet = new Set<string>(); premiumIds.forEach((id, index) => { const parsed = v.text(id, `inventory.premiumBaselineModelIds.${index}`); if (!modelSet.has(parsed)) v.issue("unknown_premium_baseline", `inventory.premiumBaselineModelIds.${index}`, "must be a member of inventory.modelIds"); if (premiumSet.has(parsed)) v.issue("duplicate_premium_baseline", `inventory.premiumBaselineModelIds.${index}`, "must be distinct"); premiumSet.add(parsed); });
  const runs = v.array(root.runs, "runs"); const runIds = new Set<string>(); const cells = new Set<string>(); const modelHashOwner = new Map<string, string>(); const outputHashOwner = new Map<string, string>(); const inputHashOwner = new Map<string, string>(); const renderHashOwner = new Map<string, string>(); const sourceOwner = new Map<string, string>(); const measurementOwner = new Map<string, string>(); const comparisonByModel = new Map<string, { sources: string; measurement: string }>();
  for (const [index, raw] of runs.entries()) { const path = `runs.${index}`; const run = v.object(raw, path, RUN_KEYS); if (!run) continue; const runId = v.text(run.runId, `${path}.runId`); if (runIds.has(runId)) v.issue("duplicate_run", `${path}.runId`, "must be unique"); runIds.add(runId); const runTenant = v.text(run.tenantId, `${path}.tenantId`); if (runTenant && tenantId && runTenant !== tenantId) v.issue("tenant_mismatch", `${path}.tenantId`, "must match inventory.tenantId"); const modelId = v.text(run.frameModelId, `${path}.frameModelId`); if (!modelSet.has(modelId)) v.issue("unknown_model", `${path}.frameModelId`, "must bind to the inventory"); const method = v.enum(run.method, `${path}.method`, BAKEOFF_METHODS); if (method === "Premium" && !premiumSet.has(modelId)) v.issue("unexpected_premium_run", `${path}.method`, "Premium is allowed only for the 3 declared baseline models"); const cell = `${modelId}\0${method}`; if (cells.has(cell)) v.issue("duplicate_cell", `${path}.method`, "must not duplicate or relabel a model/method cell"); cells.add(cell);
    const sources = v.array(run.sourceAssetSha256s, `${path}.sourceAssetSha256s`); if (sources.length === 0) v.issue("missing_source_evidence", `${path}.sourceAssetSha256s`, "must contain immutable source digests"); const ownSources = new Set<string>(); sources.forEach((value, sourceIndex) => { const hash = v.hash(value, `${path}.sourceAssetSha256s.${sourceIndex}`); if (ownSources.has(hash)) v.issue("duplicate_source", `${path}.sourceAssetSha256s.${sourceIndex}`, "must be unique within the run"); ownSources.add(hash); const owner = sourceOwner.get(hash); if (owner && owner !== modelId) v.issue("reused_source", `${path}.sourceAssetSha256s.${sourceIndex}`, `must not relabel source bytes owned by ${owner}`); else sourceOwner.set(hash, modelId); });
    const measurement = v.hash(run.measurementSha256, `${path}.measurementSha256`); const measurementPrior = measurementOwner.get(measurement); if (measurementPrior && measurementPrior !== modelId) v.issue("reused_measurement", `${path}.measurementSha256`, `must not relabel measurements owned by ${measurementPrior}`); else measurementOwner.set(measurement, modelId); if (method !== "Commercial Reference") { const canonicalSources = [...ownSources].sort().join(","); const comparison = comparisonByModel.get(modelId); if (!comparison) comparisonByModel.set(modelId, { sources: canonicalSources, measurement }); else { if (comparison.sources !== canonicalSources) v.issue("comparison_source_mismatch", `${path}.sourceAssetSha256s`, "all required methods for a model must use the same canonical source digest set"); if (comparison.measurement !== measurement) v.issue("comparison_measurement_mismatch", `${path}.measurementSha256`, "all required methods for a model must use the same measurement digest"); } }
    const generator = v.object(run.generator, `${path}.generator`, GENERATOR_KEYS); v.text(generator?.identity, `${path}.generator.identity`); v.text(generator?.version, `${path}.generator.version`); v.hash(generator?.configSha256, `${path}.generator.configSha256`); const inputHash = v.hash(run.inputSha256, `${path}.inputSha256`); const inputOwner = inputHashOwner.get(inputHash); if (inputOwner && inputOwner !== cell) v.issue("reused_artifact", `${path}.inputSha256`, `must not relabel input bytes owned by ${inputOwner.replace("\0", "/")}`); else inputHashOwner.set(inputHash, cell); const output = v.hash(run.outputSha256, `${path}.outputSha256`); v.number(run.artifactByteLength, `${path}.artifactByteLength`, true, true); const modelHash = v.hash(run.modelSha256, `${path}.modelSha256`); v.number(run.modelByteLength, `${path}.modelByteLength`, true, true);
    for (const [hash, owners, field] of [[output, outputHashOwner, "outputSha256"], [modelHash, modelHashOwner, "modelSha256"]] as const) { const owner = owners.get(hash); if (owner && owner !== cell) v.issue("reused_artifact", `${path}.${field}`, `must not relabel artifact bytes owned by ${owner.replace("\0", "/")}`); else owners.set(hash, cell); }
    const reviewTimes: Array<[string, string]> = []; const angles = v.array(run.angles, `${path}.angles`); if (angles.length !== BAKEOFF_ANGLES.length) v.issue("missing_angle", `${path}.angles`, "must contain front, 15, and 25 degree evidence"); const angleSet = new Set<string>(); angles.forEach((rawAngle, angleIndex) => { const anglePath = `${path}.angles.${angleIndex}`; const angle = v.object(rawAngle, anglePath, ANGLE_KEYS); const role = v.enum(angle?.angle, `${anglePath}.angle`, BAKEOFF_ANGLES); if (angleSet.has(role)) v.issue("duplicate_angle", `${anglePath}.angle`, "must be unique"); angleSet.add(role); const renderHash = v.hash(angle?.renderSha256, `${anglePath}.renderSha256`); const renderIdentity = `${cell}\0${role}`; const renderOwner = renderHashOwner.get(renderHash); if (renderOwner && renderOwner !== renderIdentity) v.issue("reused_artifact", `${anglePath}.renderSha256`, "must not relabel render bytes across model, method, or angle evidence"); else renderHashOwner.set(renderHash, renderIdentity); v.number(angle?.artifactByteLength, `${anglePath}.artifactByteLength`, true, true); reviewTimes.push([review(v, angle?.humanReview, `${anglePath}.humanReview`), `${anglePath}.humanReview.recordedAt`]); }); for (const angle of BAKEOFF_ANGLES) if (!angleSet.has(angle)) v.issue("missing_angle", `${path}.angles`, `missing ${angle}`);
    v.number(run.sizeErrorPct, `${path}.sizeErrorPct`); reviewTimes.push([review(v, run.materialReview, `${path}.materialReview`), `${path}.materialReview.recordedAt`]); reviewTimes.push([review(v, run.visualReview, `${path}.visualReview`), `${path}.visualReview.recordedAt`]);
    const perf = v.object(run.performance, `${path}.performance`, PERFORMANCE_KEYS); v.enum(perf?.deviceClass, `${path}.performance.deviceClass`, BAKEOFF_MOBILE_DEVICE_CLASSES); v.text(perf?.runtimeVersion, `${path}.performance.runtimeVersion`); v.number(perf?.renderFps, `${path}.performance.renderFps`, false, true); const measuredAt = v.date(perf?.measuredAt, `${path}.performance.measuredAt`); v.text(perf?.actorId, `${path}.performance.actorId`);
    v.number(run.correctionCount, `${path}.correctionCount`, true); const correctionMinutes = v.number(run.correctionMinutes, `${path}.correctionMinutes`); const approval = v.enum(run.approval, `${path}.approval`, APPROVALS); const firstPass = v.boolean(run.firstPass, `${path}.firstPass`); const failure = v.enum(run.failureClassification, `${path}.failureClassification`, FAILURES); const startedAt = v.date(run.startedAt, `${path}.startedAt`); const completedAt = v.date(run.completedAt, `${path}.completedAt`); v.text(run.actorId, `${path}.actorId`);
    if (startedAt && completedAt && Date.parse(completedAt) < Date.parse(startedAt)) v.issue("invalid_time_order", `${path}.completedAt`, "must not precede startedAt"); for (const [time, timePath] of [[completedAt, `${path}.completedAt`], [measuredAt, `${path}.performance.measuredAt`], ...reviewTimes] as const) { if (time && evaluatedAt && Date.parse(time) > Date.parse(evaluatedAt)) v.issue("future_evidence", timePath, "must not be after evaluatedAt"); if (time && completedAt && Date.parse(time) < Date.parse(completedAt)) v.issue("review_before_completion", timePath, "review/performance evidence must not precede run completion"); } if (firstPass && (correctionMinutes !== 0 || run.correctionCount !== 0 || approval !== "approve" || failure !== "none")) v.issue("invalid_first_pass", `${path}.firstPass`, "first pass requires zero correction, approval, and no failure"); if (approval === "manual-model-required" && failure !== "manual-required") v.issue("invalid_failure_binding", `${path}.failureClassification`, "manual approval requires manual-required classification");
  }
  return v.issues;
}

function object(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function median(values: number[]): number | null { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle]! : (sorted[middle - 1]! + sorted[middle]!) / 2; }

export function evaluateGenerationBakeoff(input: unknown): GenerationBakeoffEvaluation {
  const documentIssues = validateGenerationBakeoffEvidence(input); const root = object(input); const inventory = object(root?.inventory); const modelIds = Array.isArray(inventory?.modelIds) ? inventory.modelIds.filter((id): id is string => typeof id === "string") : []; const premiumIds = Array.isArray(inventory?.premiumBaselineModelIds) ? inventory.premiumBaselineModelIds.filter((id): id is string => typeof id === "string") : []; const runs = Array.isArray(root?.runs) ? root.runs.map(object).filter((run): run is Record<string, unknown> => run !== null) : [];
  const required = [...modelIds.flatMap((model) => REQUIRED_BAKEOFF_METHODS.map((method) => `${model}/${method}`)), ...premiumIds.map((model) => `${model}/Premium`)]; const requiredSet = new Set(required); const counts = new Map<string, number>(); for (const run of runs) if (typeof run.frameModelId === "string" && typeof run.method === "string") { const cell = `${run.frameModelId}/${run.method}`; if (requiredSet.has(cell)) counts.set(cell, (counts.get(cell) ?? 0) + 1); }
  const missingCells = required.filter((cell) => !counts.has(cell)); const duplicateCells = [...counts].filter(([, count]) => count > 1).map(([cell]) => cell); const presentCells = required.length - missingCells.length;
  const completenessIssues: BakeoffIssue[] = []; if (modelIds.length !== 20 || new Set(modelIds).size !== 20) completenessIssues.push({ code: "inventory_incomplete", path: "inventory.modelIds", message: "exactly 20 unique inventory models are required" }); if (premiumIds.length !== 3 || new Set(premiumIds).size !== 3 || premiumIds.some((id) => !modelIds.includes(id))) completenessIssues.push({ code: "premium_baseline_incomplete", path: "inventory.premiumBaselineModelIds", message: "exactly 3 distinct inventory models are required for Premium baselines" }); if (missingCells.length) completenessIssues.push({ code: "missing_cells", path: "runs", message: `${missingCells.length} of 43 required internal cells are missing` }); if (duplicateCells.length) completenessIssues.push({ code: "duplicate_cells", path: "runs", message: `${duplicateCells.length} required cells are duplicated` });
  const complete = documentIssues.length === 0 && completenessIssues.length === 0; const standard = runs.filter((run) => run.method === "Standard" && modelIds.includes(run.frameModelId as string)); const firstPass = standard.filter((run) => run.firstPass === true && run.approval === "approve").length; const correction = standard.map((run) => run.correctionMinutes).filter((value): value is number => typeof value === "number" && Number.isFinite(value)); const manual = standard.filter((run) => run.approval === "manual-model-required" || run.failureClassification === "manual-required").length;
  const autoPct = standard.length === 20 ? firstPass / 20 * 100 : null; const correctionMedian = standard.length === 20 && correction.length === 20 ? median(correction) : null; const manualPct = standard.length === 20 ? manual / 20 * 100 : null; const metricsDefined = complete && autoPct !== null && correctionMedian !== null && manualPct !== null; const metricsPass = metricsDefined && autoPct >= 50 && correctionMedian <= 10 && manualPct <= 25;
  const correctionOver = standard.filter((run) => typeof run.correctionMinutes === "number" && run.correctionMinutes > 15).map((run) => String(run.runId)); const mobileUnder = runs.filter((run) => requiredSet.has(`${run.frameModelId as string}/${run.method as string}`) && typeof object(run.performance)?.renderFps === "number" && (object(run.performance)?.renderFps as number) < 20).map((run) => String(run.runId)); const manualOver = manualPct !== null && manualPct > 25; const triggered = correctionOver.length > 0 || mobileUnder.length > 0 || manualOver;
  const template = typeof root?.template === "boolean" ? root.template : null;
  return { documentValidity: { valid: documentIssues.length === 0, issues: documentIssues }, evidenceCompleteness: { complete, requiredCells: modelIds.length === 20 && premiumIds.length === 3 ? 43 : 0, presentCells, missingCells, duplicateCells, issues: completenessIssues, commercialReferencePresent: runs.some((run) => run.method === "Commercial Reference") }, metrics: { defined: metricsDefined, autoFirstPassApprovalPct: autoPct, standardCorrectionMedianMinutes: correctionMedian, manualModelSharePct: manualPct, pass: metricsPass }, stopSignals: { triggered, standardCorrectionOver15: correctionOver, manualShareOver25: manualOver, mobileUnder20Fps: mobileUnder }, strategySelectionReadiness: template === false && complete && metricsPass && !triggered, template };
}
