/* Server-only PostgreSQL/PGlite reference adapter for the JSC-0219 core. */
import { canonicalJson, inspectNonProxyQaPersistencePlanIntegrity, sha256Hex, type NonProxyQaAuthorityDenials, type NonProxyQaPersistencePlan } from "../../contracts/src/index.js";
import type { CommittedReviewQaPreviewDatabase, CommittedReviewQaPreviewDatabaseSnapshot, CommittedReviewQaPreviewSelection, CommittedReviewQaPreviewTransaction } from "./committedReviewQaPreview.js";
import {
  NON_PROXY_QA_ASSET_KEYS, NON_PROXY_QA_AUTHORITY_KEYS, NON_PROXY_QA_BINDING_KEYS, NON_PROXY_QA_REVIEW_KEYS, NON_PROXY_QA_REVIEW_SELECT, NON_PROXY_QA_SOURCE_KEYS,
  reconstructNonProxyQaAssetRow, reconstructNonProxyQaAuthorityRow, reconstructNonProxyQaBindingRow, reconstructNonProxyQaReviewRow, reconstructNonProxyQaSourceRow,
  type NonProxyQaPinnedSession, type NonProxyQaPinnedSessionLease, type NonProxyQaPinnedSessionProvider,
} from "./nonProxyQaPgliteWriterDatabase.js";

type Results = { rows: unknown[]; affectedRows?: number };
type Queryable = { query(sql: string, parameters?: unknown[]): Promise<Results> };
export class CommittedReviewQaPreviewDatabaseAdapterError extends Error { constructor() { super("qa-preview database adapter failure"); this.name = "CommittedReviewQaPreviewDatabaseAdapterError"; } }
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/; const HASH = /^[a-f0-9]{64}$/; const POSITIVE_DECIMAL = /^[1-9][0-9]*$/;
function fail(): never { throw new CommittedReviewQaPreviewDatabaseAdapterError(); }
function exact(value: unknown, keys: readonly string[]): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value) || (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null)) fail(); const names = Reflect.ownKeys(value); if (names.some((key) => typeof key === "symbol") || names.length !== keys.length) fail(); const row = value as Record<string, unknown>; for (const key of keys) { const descriptor = Object.getOwnPropertyDescriptor(row, key); if (!descriptor?.enumerable || descriptor.get || descriptor.set) fail(); } for (const key of Object.keys(row)) if (!keys.includes(key)) fail(); return row; }
function text(value: unknown): string { if (typeof value !== "string") fail(); return value; }
function id(value: unknown): string { const result = text(value); if (!ID.test(result)) fail(); return result; }
function hash(value: unknown): string { const result = text(value); if (!HASH.test(result)) fail(); return result; }
function integer(value: unknown): number {
  const result = typeof value === "string" ? POSITIVE_DECIMAL.test(value) ? Number(value) : fail() : typeof value === "bigint" ? Number(value) : value;
  if (typeof result !== "number" || !Number.isSafeInteger(result) || result < 1) fail();
  return result;
}
function bool(value: unknown): boolean { if (typeof value !== "boolean") fail(); return value; }
function timestamp(value: unknown): string { const result = value instanceof Date ? Date.prototype.toISOString.call(value) : text(value); const epoch = Date.parse(result); if (!Number.isFinite(epoch)) fail(); return new Date(epoch).toISOString(); }
function literal<T extends string | boolean | null>(value: unknown, expected: T): T { if (value !== expected) fail(); return expected; }

type Budget = { nodes: number; textBytes: number; rows: number; arrayItems: number; active: WeakSet<object> };
const budgets = new WeakMap<object, Budget>();
function budgetFor(queryable: Queryable): Budget { let budget = budgets.get(queryable as object); if (!budget) { budget = { nodes: 0, textBytes: 0, rows: 0, arrayItems: 0, active: new WeakSet<object>() }; budgets.set(queryable as object, budget); } return budget; }
function driverClone(value: unknown, state: Budget, depth = 0): unknown {
  if (depth > 96 || ++state.nodes > 50_000) fail();
  if (value instanceof Date) { if (Object.getPrototypeOf(value) !== Date.prototype || Reflect.ownKeys(value).length !== 0) fail(); try { return Date.prototype.toISOString.call(value); } catch { fail(); } }
  if (Array.isArray(value)) { if (Object.getPrototypeOf(value) !== Array.prototype || value.length > 512 || Reflect.ownKeys(value).length !== value.length + 1 || state.active.has(value)) fail(); state.arrayItems += value.length; if (state.arrayItems > 8_192) fail(); state.active.add(value); const result = Array.from({ length: value.length }, (_, index) => { const descriptor = Object.getOwnPropertyDescriptor(value, String(index)); if (!descriptor?.enumerable || descriptor.get || descriptor.set) fail(); return driverClone(descriptor.value, state, depth + 1); }); state.active.delete(value); return Object.freeze(result); }
  if (typeof value === "object" && value !== null) { const keys = Reflect.ownKeys(value); if ((Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null) || keys.some((key) => typeof key === "symbol") || keys.length > 512 || state.active.has(value)) fail(); state.active.add(value); const result: Record<string, unknown> = {}; for (const key of keys as string[]) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor?.enumerable || descriptor.get || descriptor.set) fail(); const length = new TextEncoder().encode(key).byteLength; state.textBytes += length; if (length > 1_024 || state.textBytes > 8 * 1024 * 1024) fail(); Object.defineProperty(result, key, { value: driverClone(descriptor.value, state, depth + 1), enumerable: true, writable: false, configurable: false }); } state.active.delete(value); return Object.freeze(result); }
  if (typeof value === "string") { const length = new TextEncoder().encode(value).byteLength; state.textBytes += length; if (length > 1_000_000 || state.textBytes > 8 * 1024 * 1024) fail(); return value; }
  if (value === null || typeof value === "boolean" || typeof value === "number" && Number.isFinite(value) || typeof value === "bigint") return value;
  fail();
}
async function rows(queryable: Queryable, sql: string, parameters: unknown[], keys: readonly string[], maximum = 1): Promise<readonly Record<string, unknown>[]> { const budget = budgetFor(queryable); const raw = await queryable.query(sql, parameters); if (typeof raw !== "object" || raw === null || Array.isArray(raw) || (Object.getPrototypeOf(raw) !== Object.prototype && Object.getPrototypeOf(raw) !== null)) fail(); const rawKeys = Reflect.ownKeys(raw); if (rawKeys.some((key) => typeof key === "symbol") || rawKeys.length > 32) fail(); for (const key of rawKeys as string[]) { const descriptor = Object.getOwnPropertyDescriptor(raw, key); if (!descriptor || descriptor.get || descriptor.set) fail(); } const descriptor = Object.getOwnPropertyDescriptor(raw, "rows"); if (!descriptor || !Array.isArray(descriptor.value) || descriptor.value.length > maximum) fail(); const cloned = driverClone(descriptor.value, budget); if (!Array.isArray(cloned)) fail(); budget.rows += cloned.length; if (budget.rows > 128) fail(); return Object.freeze(cloned.map((item) => exact(item, keys))); }
async function one(queryable: Queryable, sql: string, parameters: unknown[], keys: readonly string[]): Promise<Record<string, unknown>> { const found = await rows(queryable, sql, parameters, keys, 1); if (found.length !== 1) fail(); return found[0]!; }

type Locator = Readonly<{ tenantId: string; authorityId: string; keyId: string; assetVersionId: string; assetVersion: number; generationJobId: string }>;
const LOCATOR_KEYS = ["generation_job_id", "reviewer_authority_id", "reviewer_key_id"] as const;
async function locate(queryable: Queryable, selection: CommittedReviewQaPreviewSelection): Promise<Locator> { const row = await one(queryable, "select generation_job_id,reviewer_authority_id,reviewer_key_id from private.non_proxy_human_qa_records where tenant_id=$1 and candidate_asset_version_id=$2 and candidate_version=$3", [selection.tenantId, selection.assetVersionId, selection.assetVersion], LOCATOR_KEYS); return Object.freeze({ tenantId: selection.tenantId, authorityId: id(row.reviewer_authority_id), keyId: id(row.reviewer_key_id), assetVersionId: selection.assetVersionId, assetVersion: selection.assetVersion, generationJobId: id(row.generation_job_id) }); }
function part(value: string): string { return `${value.length}:${value}`; }
function lockKeys(identity: Locator): readonly string[] { return Object.freeze([`authority:${part(identity.tenantId)}${part(identity.authorityId)}${part(identity.keyId)}`, `candidate:${part(identity.tenantId)}${part(identity.assetVersionId)}:${identity.assetVersion}`, `job:${part(identity.tenantId)}${part(identity.generationJobId)}`]); }
function sameLocator(left: Locator, right: Locator): boolean { return canonicalJson(left) === canonicalJson(right); }

const DENIALS: NonProxyQaAuthorityDenials = Object.freeze({ databaseMutation: false, assetVersionCreated: false, assetVersionPromoted: false, qaPreviewAdmitted: false, runtimeAdmitted: false, publicLiveAdmitted: false, recommendedForLive: false, catalogAuthority: false, activeDeployment: false, deploymentAuthority: false, publication: false, publicationAuthority: false, g1: false, g2: false, g3: false, g4: false, g5: false, g6: false, g7: false });
const JOB_KEYS = ["tenant_id", "id", "frame_model_id", "canonical_input_sha256", "generator_input_sha256", "source_asset_sha256s", "measurement_set_sha256", "head_type", "head_sha256", "head_manifest_sha256", "head_manifest_byte_length", "head_model_sha256", "head_model_byte_length"] as const;
const MEASUREMENT_KEYS = ["id", "tenant_id", "frame_model_id", "specimen_id", "evidence_sha256", "status"] as const;
const VARIANT_KEYS = ["id", "tenant_id", "frame_model_id"] as const;
const SOURCE_JOIN_KEYS = [...NON_PROXY_QA_SOURCE_KEYS, "authoritative_source_sha256", "authoritative_source_frame_model_id", "authoritative_source_frame_variant_id"] as const;

async function reconstructPlan(queryable: Queryable, selection: CommittedReviewQaPreviewSelection): Promise<Readonly<{ plan: NonProxyQaPersistencePlan; job: Record<string, unknown>; measurement: Record<string, unknown>; variant: Record<string, unknown> }>> {
  const reviewRaw = await one(queryable, `select ${NON_PROXY_QA_REVIEW_SELECT} from private.non_proxy_human_qa_records where tenant_id=$1 and candidate_asset_version_id=$2 and candidate_version=$3`, [selection.tenantId, selection.assetVersionId, selection.assetVersion], NON_PROXY_QA_REVIEW_KEYS);
  // v1/v2 and partially written v3 rows have no trusted writer commit marker.
  // The shared projection also checks this pair; retaining the explicit check
  // here makes the preview adapter's post-v3 admission dependency unmistakable.
  const committedAt = text(reviewRaw.writer_committed_at_canonical); if (timestamp(committedAt) !== timestamp(reviewRaw.writer_committed_at)) fail();
  const review = reconstructNonProxyQaReviewRow(reviewRaw);
  const authority = reconstructNonProxyQaAuthorityRow(await one(queryable, `select ${NON_PROXY_QA_AUTHORITY_KEYS.join(",")} from private.qa_reviewer_authorities where tenant_id=$1 and id=$2`, [selection.tenantId, review.reviewerAuthorityRowId], NON_PROXY_QA_AUTHORITY_KEYS));
  const asset = reconstructNonProxyQaAssetRow(await one(queryable, `select ${NON_PROXY_QA_ASSET_KEYS.join(",")} from private.asset_versions where tenant_id=$1 and id=$2 and version=$3`, [selection.tenantId, selection.assetVersionId, selection.assetVersion], NON_PROXY_QA_ASSET_KEYS));
  const binding = reconstructNonProxyQaBindingRow(await one(queryable, `select ${NON_PROXY_QA_BINDING_KEYS.join(",")} from private.non_proxy_asset_version_bindings where tenant_id=$1 and asset_version_id=$2`, [selection.tenantId, selection.assetVersionId], NON_PROXY_QA_BINDING_KEYS));
  const sourceRaw = await rows(queryable, `select ${NON_PROXY_QA_SOURCE_KEYS.map((key) => `s.${key}`).join(",")},a.sha256 authoritative_source_sha256,a.frame_model_id authoritative_source_frame_model_id,a.frame_variant_id authoritative_source_frame_variant_id from private.asset_version_sources s join private.source_assets a on a.tenant_id=s.tenant_id and a.id=s.source_asset_id where s.tenant_id=$1 and s.asset_version_id=$2 order by s.source_sha256 limit 33`, [selection.tenantId, selection.assetVersionId], SOURCE_JOIN_KEYS, 33);
  if (sourceRaw.length < 1 || sourceRaw.length > 32) fail();
  const sourceRows = sourceRaw.map((raw) => { if (hash(raw.authoritative_source_sha256) !== hash(raw.source_sha256) || id(raw.authoritative_source_frame_model_id) !== id(raw.frame_model_id)) fail(); const sourceVariant = raw.authoritative_source_frame_variant_id === null ? null : id(raw.authoritative_source_frame_variant_id); if (sourceVariant !== null && sourceVariant !== id(raw.frame_variant_id)) fail(); return reconstructNonProxyQaSourceRow(Object.fromEntries(NON_PROXY_QA_SOURCE_KEYS.map((key) => [key, raw[key]]))); });
  const job = await one(queryable, `select j.tenant_id,j.id,j.frame_model_id,j.canonical_input_sha256,j.generator_input_sha256,to_jsonb(j.source_asset_sha256s) source_asset_sha256s,j.measurement_set_sha256,h.event_type head_type,h.event_sha256 head_sha256,h.output_manifest_sha256 head_manifest_sha256,h.output_manifest_byte_length head_manifest_byte_length,h.output_model_sha256 head_model_sha256,h.output_model_byte_length head_model_byte_length from private.generation_jobs j join lateral (select event_type,event_sha256,output_manifest_sha256,output_manifest_byte_length,output_model_sha256,output_model_byte_length from private.generation_job_events where tenant_id=j.tenant_id and generation_job_id=j.id order by sequence desc limit 1) h on true where j.tenant_id=$1 and j.id=$2`, [selection.tenantId, review.generationJobId], JOB_KEYS);
  if (hash(job.canonical_input_sha256) !== review.canonicalInputSha256 || hash(job.generator_input_sha256) !== review.generatorInputSha256) fail();
  const measurement = await one(queryable, "select id,tenant_id,frame_model_id,specimen_id,evidence_sha256,status from private.measurement_sets where tenant_id=$1 and id=$2", [selection.tenantId, review.measurementSetId], MEASUREMENT_KEYS);
  const variant = await one(queryable, "select id,tenant_id,frame_model_id from private.frame_variants where tenant_id=$1 and id=$2", [selection.tenantId, review.frameVariantId], VARIANT_KEYS);
  const body = { schemaVersion: 1 as const, planType: "non-proxy-qa-persistence-row-projections" as const, decision: "approve" as const, reviewerAuthority: authority, reviewRecord: review, assetVersion: asset, binding, sourceRows, authority: DENIALS };
  const planSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/persistence-plan/v1", body }));
  const plan = await inspectNonProxyQaPersistencePlanIntegrity({ ...body, planSha256, idempotencyKey: `nqpp_${planSha256}` });
  if (plan.decision !== "approve" || !plan.assetVersion || !plan.binding) fail();
  return Object.freeze({ plan, job, measurement, variant });
}
function strictHashes(value: unknown): readonly string[] { if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype || value.length < 1 || value.length > 32 || Reflect.ownKeys(value).length !== value.length + 1) fail(); const result = value.map((item, index) => { const descriptor = Object.getOwnPropertyDescriptor(value, String(index)); if (!descriptor?.enumerable || descriptor.get || descriptor.set) fail(); return hash(descriptor.value); }); if (new Set(result).size !== result.length || result.some((item, index) => index > 0 && result[index - 1]! >= item)) fail(); return Object.freeze(result); }

async function readSnapshot(queryable: Queryable, selection: CommittedReviewQaPreviewSelection): Promise<CommittedReviewQaPreviewDatabaseSnapshot> {
  const { plan, job, measurement, variant } = await reconstructPlan(queryable, selection); const asset = plan.assetVersion ?? fail(); const binding = plan.binding ?? fail(); const review = plan.reviewRecord; const authority = plan.reviewerAuthority;
  const jobSources = strictHashes(job.source_asset_sha256s); const sourceSetSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/source-set/v1", sourceAssetSha256s: jobSources }));
  return Object.freeze({ schemaVersion: 1,
    asset: Object.freeze({ tenantId: asset.tenantId, id: asset.id, version: asset.version, frameModelId: asset.frameModelId, frameVariantId: asset.frameVariantId, generationJobId: asset.generationJobId, status: asset.status, fixtureStatus: asset.fixtureStatus, admission: asset.admission, rightsScope: asset.rightsScope, recommendedForLive: asset.recommendedForLive, publicationEligible: asset.publicationEligible, rowSha256: asset.rowSha256, quality: asset.quality, generationMethod: asset.generationMethod, reviewStatus: asset.reviewStatus, nonProxyInternalReview: true as const, promotable: asset.promotable, sourceSetSha256: asset.sourceSetSha256, attachmentMatrix: asset.attachmentMatrix, qualityEnvelope: asset.qualityEnvelope, manifestUrl: asset.manifestUrl, manifestSha256: asset.manifestSha256, manifestByteLength: asset.manifestByteLength, modelUrl: asset.modelUrl, modelSha256: asset.modelSha256, modelByteLength: asset.modelByteLength }),
    binding: Object.freeze({ assetVersionId: binding.assetVersionId, reviewRecordId: binding.reviewRecordId, tenantId: binding.tenantId, frameModelId: binding.frameModelId, frameVariantId: binding.frameVariantId, generationJobId: binding.generationJobId, sourceSetSha256: binding.sourceSetSha256, effectiveValidUntil: binding.effectiveValidUntil, rightsScope: binding.rightsScope, recommendedForLive: binding.recommendedForLive, publicationEligible: binding.publicationEligible, rowSha256: binding.rowSha256, assetVersionRowSha256: binding.assetVersionRowSha256, decisionPayloadSha256: binding.decisionPayloadSha256, qualityEnvelope: binding.qualityEnvelope }),
    review: Object.freeze({ id: review.id, tenantId: review.tenantId, decision: literal(review.decision, "approve"), terminal: literal(review.terminal, true), reviewerAuthorityRowId: review.reviewerAuthorityRowId, reviewerAuthorityId: review.reviewerAuthorityId, reviewerId: review.reviewerId, reviewerKeyId: review.reviewerKeyId, reviewerPublicKeyFingerprintSha256: review.reviewerPublicKeyFingerprintSha256, generationJobId: review.generationJobId, frameModelId: review.frameModelId, frameVariantId: review.frameVariantId, reviewHeadEventSha256: review.reviewHeadEventSha256, sourceSetSha256: review.sourceSetSha256, candidateAssetVersionId: review.candidateAssetVersionId, candidateVersion: review.candidateVersion, outputManifestSha256: review.output.manifestSha256, outputManifestByteLength: review.output.manifestByteLength, outputModelSha256: review.output.modelSha256, outputModelByteLength: review.output.modelByteLength, sourceAssetSha256s: review.sourceAssetSha256s, measurementSetId: review.measurementSetId, measurementSetSha256: review.measurementSetSha256, specimenId: review.specimenId, effectiveValidUntil: review.effectiveValidUntil, rightsScope: review.rightsScope, rowSha256: review.rowSha256, decisionPayloadSha256: review.decisionPayloadSha256, approvedAssetVersionRowSha256: hash(review.approvedAssetVersionRowSha256), approvedAttachmentMatrix: asset.attachmentMatrix, approvedQualityEnvelope: review.approvedQualityEnvelope ?? fail() }),
    reviewerAuthority: Object.freeze({ id: authority.id, tenantId: authority.tenantId, authorityId: authority.authorityId, reviewerId: authority.reviewerId, status: literal(authority.status, "active"), scope: literal(authority.scope, "non-proxy-human-qa-decision"), revokedAt: literal(authority.revokedAt, null), rowSha256: authority.rowSha256, keyId: authority.keyId, publicKeyFingerprintSha256: authority.publicKeyFingerprintSha256 }),
    generationJob: Object.freeze({ id: id(job.id), tenantId: id(job.tenant_id), frameModelId: id(job.frame_model_id), currentHeadEventSha256: hash(job.head_sha256), currentHeadEventType: literal(job.head_type, "output-recorded"), currentOutputManifestSha256: hash(job.head_manifest_sha256), currentOutputModelSha256: hash(job.head_model_sha256), currentOutputManifestByteLength: integer(job.head_manifest_byte_length), currentOutputModelByteLength: integer(job.head_model_byte_length), sourceSetSha256, sourceAssetSha256s: jobSources, measurementSetSha256: hash(job.measurement_set_sha256) }),
    measurementSet: Object.freeze({ id: id(measurement.id), tenantId: id(measurement.tenant_id), frameModelId: id(measurement.frame_model_id), specimenId: id(measurement.specimen_id), sha256: hash(measurement.evidence_sha256), status: literal(measurement.status, "verified") }),
    variant: Object.freeze({ id: id(variant.id), tenantId: id(variant.tenant_id), frameModelId: id(variant.frame_model_id) }), assetSourceSha256s: Object.freeze(plan.sourceRows.map((source) => source.sourceSha256)),
  });
}
function transactionPort(transaction: Queryable): CommittedReviewQaPreviewTransaction { return Object.freeze({ async transactionTimestamp() { const row = await one(transaction, "select transaction_timestamp()::text as observed_at", [], ["observed_at"]); return timestamp(row.observed_at); }, readAuthoritativeSnapshot(selection: CommittedReviewQaPreviewSelection) { return readSnapshot(transaction, selection); }, async finalRecheck(selection: CommittedReviewQaPreviewSelection) { const snapshot = await readSnapshot(transaction, selection); const row = await one(transaction, "select clock_timestamp()::text as clock_timestamp", [], ["clock_timestamp"]); return Object.freeze({ snapshot, clockTimestamp: timestamp(row.clock_timestamp) }); } }); }
async function discard(lease: NonProxyQaPinnedSessionLease | null): Promise<void> { try { await lease?.discard(); } catch { /* quarantined even when close fails */ } }

export function createPgliteCommittedReviewQaPreviewDatabase(sessions: NonProxyQaPinnedSessionProvider): CommittedReviewQaPreviewDatabase {
  return Object.freeze({ async readonly<T>(selection: CommittedReviewQaPreviewSelection, work: (transaction: CommittedReviewQaPreviewTransaction) => Promise<T>): Promise<T> {
    let leaseRef: NonProxyQaPinnedSessionLease | null = null; let providerCallbackCompleted = false; let providerCalls = 0; let finalValue!: T; const providerSentinel = Object.freeze({ token: Object.freeze({}) });
    try { const providerResult = await sessions.withPinnedSession(async (lease) => {
      providerCalls += 1; if (providerCalls !== 1) { await discard(leaseRef); await discard(lease); fail(); }
      leaseRef = lease; const session: NonProxyQaPinnedSession = lease.session; const budget: Budget = { nodes: 0, textBytes: 0, rows: 0, arrayItems: 0, active: new WeakSet<object>() }; budgets.set(session as object, budget);
      let acquisitionUnknown = false; let roleStateUnknown = false; let primaryPresent = false; let primary: unknown; let result!: T; const acquired: string[] = [];
      try {
        await session.query("set lock_timeout = '5s'"); await session.query("set statement_timeout = '15s'");
        try { await session.query("set role jessica_committed_review_qa_preview_reader"); } catch (error) { roleStateUnknown = true; throw error; }
        const locator = await locate(session, selection);
        for (const key of lockKeys(locator)) { try { await session.query("select pg_catalog.pg_advisory_lock(pg_catalog.hashtextextended($1,218))", [key]); } catch (error) { acquisitionUnknown = true; throw error; } acquired.push(key); }
        let entered = 0; let callbackCompleted = false; let callbackErrorPresent = false; let callbackError: unknown; const transactionSentinel = Object.freeze({ token: Object.freeze({}) });
        try { const transactionResult = await session.transaction(async (transaction) => { entered += 1; if (entered !== 1) fail(); budgets.set(transaction as object, budget); try { await transaction.query("set transaction isolation level repeatable read, read only"); await transaction.query("set local search_path = pg_catalog, private"); await transaction.query("set local statement_timeout = '15s'"); await transaction.query("set local idle_in_transaction_session_timeout = '15s'"); const lockedLocator = await locate(transaction, selection); if (!sameLocator(locator, lockedLocator)) fail(); result = await work(transactionPort(transaction)); callbackCompleted = true; return transactionSentinel; } catch (error) { callbackErrorPresent = true; callbackError = error; throw error; } finally { budgets.delete(transaction as object); } }); if (entered !== 1 || !callbackCompleted || transactionResult !== transactionSentinel) { await discard(lease); fail(); } }
        catch (error) { const identitySafe = (typeof callbackError === "object" && callbackError !== null) || typeof callbackError === "function"; const confirmedRollback = entered && callbackErrorPresent && !callbackCompleted && identitySafe && error === callbackError; if (!confirmedRollback) await discard(lease); throw error; }
      } catch (error) { primaryPresent = true; primary = error; }
      let cleanupFailed = false;
      for (const key of acquired.reverse()) { try { const row = await one(session, "select pg_catalog.pg_advisory_unlock(pg_catalog.hashtextextended($1,218)) as unlocked", [key], ["unlocked"]); if (!bool(row.unlocked)) fail(); } catch { cleanupFailed = true; } }
      try { await session.query("reset role"); } catch { cleanupFailed = true; }
      try { await session.query("reset lock_timeout"); await session.query("reset statement_timeout"); } catch { cleanupFailed = true; }
      budgets.delete(session as object);
      if (cleanupFailed || acquisitionUnknown || roleStateUnknown) await discard(lease);
      if (primaryPresent) throw primary; if (cleanupFailed) fail(); finalValue = result; providerCallbackCompleted = true; return providerSentinel;
    });
      if (providerCalls !== 1 || providerResult !== providerSentinel) { await discard(leaseRef); fail(); }
      return finalValue;
    } catch (error) { if (providerCallbackCompleted) await discard(leaseRef); throw error; }
  } });
}
