import {
  NON_PROXY_HUMAN_QA_SCOPE,
  canonicalJson,
  nonProxyHumanQaPublicJwkFingerprintSha256,
  parseFormalizationCandidate,
  inspectNonProxyQaPersistencePlanIntegrity,
  parseNonProxyHumanQaDecisionAttestation,
  sha256Hex,
  type NonProxyAssetVersionBindingRow,
  type NonProxyAssetVersionRow,
  type NonProxyAssetVersionSourceRow,
  type NonProxyHumanQaRecordRow,
  type NonProxyQaControlPlaneSnapshot,
  type NonProxyQaPersistencePlan,
  type NonProxyQaReviewerAuthorityRow,
} from "../../contracts/src/index.js";
import { evaluateNonProxyHumanQaDecision } from "./nonProxyHumanQaDecision.js";

const REQUEST_KEYS = ["humanQaRequest"] as const;
const CONTEXT_KEYS = ["humanQaContext", "controlPlaneSnapshot"] as const;
const SNAPSHOT_KEYS = ["schemaVersion", "observedAt", "tenantId", "frameModelId", "frameVariantId", "generationJob", "sourceMappings", "measurementSet", "candidateAssetVersion", "existingRows", "reviewerAuthority", "reviewPolicy"] as const;
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const HASH = /^[a-f0-9]{64}$/;
const UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?Z$/;
const TYPED_ARRAY_BYTE_LENGTH = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(Uint8Array.prototype), "byteLength")?.get;

function object(value: unknown, path: string): asserts value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value) || (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null)) throw new TypeError(`${path} must be a plain object`);
  const ownKeys = Reflect.ownKeys(value); if (ownKeys.length > 512) throw new TypeError(`${path} exceeds the object-width budget`); if (ownKeys.some((key) => typeof key === "symbol")) throw new TypeError(`${path} must be a plain object`);
  for (const key of ownKeys) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor?.enumerable || descriptor.get || descriptor.set) throw new TypeError(`${path} fields must be enumerable data properties`); }
}
function exact(value: Record<string, unknown>, keys: readonly string[], path: string): void { const allowed = new Set(keys); const unknown = Object.keys(value).find((key) => !allowed.has(key)); const missing = keys.find((key) => !Object.hasOwn(value, key)); if (unknown) throw new TypeError(`${path}.${unknown} is not allowed`); if (missing) throw new TypeError(`${path}.${missing} is required`); }
function array(value: unknown, path: string, maximum: number): asserts value is unknown[] { if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype || value.length > maximum || Object.getOwnPropertySymbols(value).length !== 0 || Object.keys(value).length !== value.length) throw new TypeError(`${path} must be a bounded dense plain array`); const descriptors = Object.getOwnPropertyDescriptors(value); for (let index = 0; index < value.length; index += 1) { const descriptor = descriptors[String(index)]; if (!descriptor?.enumerable || descriptor.get || descriptor.set) throw new TypeError(`${path} items must be enumerable data properties`); } }
function id(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || !ID.test(value)) throw new TypeError(`${path} must be a bounded identifier`); }
function hash(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || !HASH.test(value)) throw new TypeError(`${path} must be a lowercase SHA-256 digest`); }
function positive(value: unknown, path: string): asserts value is number { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 1) throw new TypeError(`${path} must be a positive safe integer`); }
function reviewAge(value: unknown, path: string): asserts value is number { positive(value, path); if (value > 366 * 24 * 60 * 60 * 1000) throw new TypeError(`${path} exceeds the review-policy budget`); }
function timestamp(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || !UTC.test(value)) throw new TypeError(`${path} must be a canonical UTC timestamp`); const parsed = Date.parse(value); const match = /^(.*:\d{2})(?:\.(\d{1,3}))?Z$/.exec(value); const normalized = match ? `${match[1]}.${(match[2] ?? "").padEnd(3, "0")}Z` : ""; if (!Number.isFinite(parsed) || new Date(parsed).toISOString() !== normalized) throw new TypeError(`${path} must be a real canonical UTC instant`); }
function same(left: unknown, right: unknown): boolean { return canonicalJson(left) === canonicalJson(right); }
function deepFreeze<T>(value: T): T { if (typeof value === "object" && value !== null && !Object.isFrozen(value)) { for (const item of Object.values(value as Record<string, unknown>)) deepFreeze(item); Object.freeze(value); } return value; }

function snapshot(value: unknown, path: string, state = { nodes: 0, bytes: 0, textBytes: 0, active: new WeakSet<object>() }, depth = 0): unknown {
  if (depth > 96) throw new TypeError("persistence request exceeds the nesting-depth budget");
  state.nodes += 1; if (state.nodes > 30_000) throw new TypeError("persistence request exceeds the structural budget");
  if (value instanceof Uint8Array) { let byteLength: number; try { if (!TYPED_ARRAY_BYTE_LENGTH) throw new TypeError(); byteLength = TYPED_ARRAY_BYTE_LENGTH.call(value) as number; } catch { throw new TypeError(`${path} must be a genuine Uint8Array`); } state.bytes += byteLength; if (!Number.isSafeInteger(state.bytes) || state.bytes > 512 * 1024 * 1024) throw new TypeError("persistence request exceeds the byte budget"); return new Uint8Array(value); }
  if (typeof value === "object" && value !== null) { if (state.active.has(value)) throw new TypeError(`${path} must not contain cyclic object references`); state.active.add(value); }
  if (Array.isArray(value)) { array(value, path, 512); const copy = new Array<unknown>(value.length); for (let index = 0; index < value.length; index += 1) { const descriptor = Object.getOwnPropertyDescriptor(value, String(index)); if (!descriptor?.enumerable || descriptor.get || descriptor.set) throw new TypeError(`${path}.${index} must be an enumerable data property`); Object.defineProperty(copy, String(index), { value: snapshot(descriptor.value, `${path}.${index}`, state, depth + 1), writable: true, configurable: true, enumerable: true }); } state.active.delete(value); return copy; }
  if (typeof value === "object" && value !== null) { object(value, path); const copy = Object.create(null) as Record<string, unknown>; for (const key of Object.keys(value)) { state.textBytes += new TextEncoder().encode(key).byteLength; if (!Number.isSafeInteger(state.textBytes) || state.textBytes > 16 * 1024 * 1024) throw new TypeError("persistence request exceeds the aggregate text budget"); const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor?.enumerable || descriptor.get || descriptor.set) throw new TypeError(`${path}.${key} must be an enumerable data property`); Object.defineProperty(copy, key, { value: snapshot(descriptor.value, `${path}.${key}`, state, depth + 1), writable: true, configurable: true, enumerable: true }); } state.active.delete(value); return copy; }
  if (typeof value === "string") { const length = new TextEncoder().encode(value).byteLength; if (length > 1_000_000) throw new TypeError(`${path} exceeds the string budget`); state.textBytes += length; if (!Number.isSafeInteger(state.textBytes) || state.textBytes > 16 * 1024 * 1024) throw new TypeError("persistence request exceeds the aggregate text budget"); }
  return value;
}

function parseOutput(value: unknown, path: string) { object(value, path); exact(value, ["manifestSha256", "modelSha256", "manifestByteLength", "modelByteLength"], path); hash(value.manifestSha256, `${path}.manifestSha256`); hash(value.modelSha256, `${path}.modelSha256`); positive(value.manifestByteLength, `${path}.manifestByteLength`); positive(value.modelByteLength, `${path}.modelByteLength`); return structuredClone(value) as NonProxyQaControlPlaneSnapshot["generationJob"]["output"]; }

function parsePublicJwk(value: unknown): JsonWebKey { object(value, "control-plane reviewer publicJwk"); exact(value, ["key_ops", "ext", "kty", "x", "y", "crv", "use", "alg"], "control-plane reviewer publicJwk"); array(value.key_ops, "control-plane reviewer publicJwk.key_ops", 1); if (value.key_ops.length !== 1 || value.key_ops[0] !== "verify" || value.ext !== true || value.kty !== "EC" || value.crv !== "P-256" || value.use !== "sig" || value.alg !== "ES256" || typeof value.x !== "string" || typeof value.y !== "string") throw new TypeError("control-plane reviewer public JWK must be ES256 verify-only"); return structuredClone(value) as JsonWebKey; }

function parseControlPlaneSnapshot(value: unknown): NonProxyQaControlPlaneSnapshot {
  object(value, "control-plane snapshot"); exact(value, SNAPSHOT_KEYS, "control-plane snapshot"); if (value.schemaVersion !== 1) throw new TypeError("control-plane snapshot schemaVersion must be 1"); timestamp(value.observedAt, "control-plane snapshot.observedAt");
  for (const key of ["tenantId", "frameModelId", "frameVariantId"] as const) id(value[key], `control-plane snapshot.${key}`);
  object(value.generationJob, "control-plane snapshot.generationJob"); exact(value.generationJob, ["id", "canonicalInputSha256", "reviewHeadEventSha256", "generatorInputSha256", "output"], "control-plane snapshot.generationJob"); id(value.generationJob.id, "control-plane snapshot generation job id"); for (const key of ["canonicalInputSha256", "reviewHeadEventSha256", "generatorInputSha256"] as const) hash(value.generationJob[key], `control-plane snapshot.generationJob.${key}`); const output = parseOutput(value.generationJob.output, "control-plane snapshot.generationJob.output");
  array(value.sourceMappings, "control-plane snapshot.sourceMappings", 32); const mappings = value.sourceMappings.map((item, index) => { object(item, `sourceMappings.${index}`); exact(item, ["sourceAssetSha256", "sourceAssetId"], `sourceMappings.${index}`); hash(item.sourceAssetSha256, `sourceMappings.${index}.sourceAssetSha256`); id(item.sourceAssetId, `sourceMappings.${index}.sourceAssetId`); return { sourceAssetSha256: item.sourceAssetSha256, sourceAssetId: item.sourceAssetId }; });
  if (mappings.length === 0 || new Set(mappings.map((item) => item.sourceAssetSha256)).size !== mappings.length || new Set(mappings.map((item) => item.sourceAssetId)).size !== mappings.length || !same(mappings, [...mappings].sort((a, b) => a.sourceAssetSha256.localeCompare(b.sourceAssetSha256)))) throw new TypeError("control-plane source mapping must be non-empty, unique, and canonical by source hash");
  object(value.measurementSet, "control-plane snapshot.measurementSet"); exact(value.measurementSet, ["id", "sha256"], "control-plane snapshot.measurementSet"); id(value.measurementSet.id, "measurementSet.id"); hash(value.measurementSet.sha256, "measurementSet.sha256");
  object(value.candidateAssetVersion, "control-plane snapshot.candidateAssetVersion"); exact(value.candidateAssetVersion, ["id", "version"], "control-plane snapshot.candidateAssetVersion"); id(value.candidateAssetVersion.id, "candidateAssetVersion.id"); positive(value.candidateAssetVersion.version, "candidateAssetVersion.version");
  object(value.existingRows, "control-plane snapshot.existingRows"); exact(value.existingRows, ["reviewerAuthority", "reviewRecord", "assetVersion", "binding", "sourceRows"], "control-plane snapshot.existingRows");
  const existing = (entry: unknown, path: string) => { if (entry === null) return null; object(entry, path); exact(entry, ["id", "rowSha256"], path); id(entry.id, `${path}.id`); hash(entry.rowSha256, `${path}.rowSha256`); return { id: entry.id, rowSha256: entry.rowSha256 }; };
  const reviewerAuthorityExisting = existing(value.existingRows.reviewerAuthority, "existingRows.reviewerAuthority"); const reviewRecordExisting = existing(value.existingRows.reviewRecord, "existingRows.reviewRecord"); const assetVersionExisting = existing(value.existingRows.assetVersion, "existingRows.assetVersion"); const bindingExisting = existing(value.existingRows.binding, "existingRows.binding"); array(value.existingRows.sourceRows, "existingRows.sourceRows", 32); const sourceRowsExisting = value.existingRows.sourceRows.map((item, index) => existing(item, `existingRows.sourceRows.${index}`)!);
  const terminalAbsent = reviewRecordExisting === null && assetVersionExisting === null && bindingExisting === null && sourceRowsExisting.length === 0; const terminalRetry = reviewRecordExisting !== null;
  if (!terminalAbsent && !terminalRetry) throw new TypeError("existing terminal row snapshot must be wholly absent or contain an exact retry head");
  object(value.reviewerAuthority, "control-plane snapshot.reviewerAuthority"); exact(value.reviewerAuthority, ["authorityId", "keyId", "reviewerId", "scope", "publicKeyFingerprintSha256", "publicJwk", "status", "createdAt", "revokedAt"], "control-plane snapshot.reviewerAuthority"); for (const key of ["authorityId", "keyId", "reviewerId"] as const) id(value.reviewerAuthority[key], `reviewerAuthority.${key}`); if (value.reviewerAuthority.scope !== NON_PROXY_HUMAN_QA_SCOPE || value.reviewerAuthority.status !== "active" || value.reviewerAuthority.revokedAt !== null) throw new TypeError("reviewer authority snapshot must be active and scoped only to terminal human QA"); hash(value.reviewerAuthority.publicKeyFingerprintSha256, "reviewerAuthority.publicKeyFingerprintSha256"); timestamp(value.reviewerAuthority.createdAt, "reviewerAuthority.createdAt"); const publicJwk = parsePublicJwk(value.reviewerAuthority.publicJwk);
  object(value.reviewPolicy, "control-plane snapshot.reviewPolicy"); exact(value.reviewPolicy, ["maximumReviewAgeMs", "sha256"], "control-plane snapshot.reviewPolicy"); reviewAge(value.reviewPolicy.maximumReviewAgeMs, "reviewPolicy.maximumReviewAgeMs"); hash(value.reviewPolicy.sha256, "reviewPolicy.sha256");
  return { schemaVersion: 1, observedAt: value.observedAt, tenantId: value.tenantId, frameModelId: value.frameModelId, frameVariantId: value.frameVariantId, generationJob: { id: value.generationJob.id, canonicalInputSha256: value.generationJob.canonicalInputSha256, reviewHeadEventSha256: value.generationJob.reviewHeadEventSha256, generatorInputSha256: value.generationJob.generatorInputSha256, output }, sourceMappings: mappings, measurementSet: { id: value.measurementSet.id, sha256: value.measurementSet.sha256 }, candidateAssetVersion: { id: value.candidateAssetVersion.id, version: value.candidateAssetVersion.version }, existingRows: { reviewerAuthority: reviewerAuthorityExisting, reviewRecord: reviewRecordExisting, assetVersion: assetVersionExisting, binding: bindingExisting, sourceRows: sourceRowsExisting }, reviewerAuthority: { authorityId: value.reviewerAuthority.authorityId, keyId: value.reviewerAuthority.keyId, reviewerId: value.reviewerAuthority.reviewerId, scope: NON_PROXY_HUMAN_QA_SCOPE, publicKeyFingerprintSha256: value.reviewerAuthority.publicKeyFingerprintSha256, publicJwk, status: "active", createdAt: value.reviewerAuthority.createdAt, revokedAt: null }, reviewPolicy: { maximumReviewAgeMs: value.reviewPolicy.maximumReviewAgeMs, sha256: value.reviewPolicy.sha256 } } as unknown as NonProxyQaControlPlaneSnapshot;
}

async function row<T extends Record<string, unknown>>(domain: string, prefix: string, body: T): Promise<T & { id: string; rowSha256: string }> { const rowSha256 = await sha256Hex(canonicalJson({ domain, body })); return { id: `${prefix}_${rowSha256}`, rowSha256, ...body }; }

const DENIALS = deepFreeze({ databaseMutation: false, assetVersionCreated: false, assetVersionPromoted: false, qaPreviewAdmitted: false, runtimeAdmitted: false, publicLiveAdmitted: false, recommendedForLive: false, catalogAuthority: false, activeDeployment: false, deploymentAuthority: false, publication: false, publicationAuthority: false, g1: false, g2: false, g3: false, g4: false, g5: false, g6: false, g7: false } as const);

export async function evaluateNonProxyQaPersistencePlan(value: unknown, contextValue: unknown): Promise<NonProxyQaPersistencePlan> {
  object(value, "persistence request"); exact(value, REQUEST_KEYS, "persistence request"); object(contextValue, "persistence context"); exact(contextValue, CONTEXT_KEYS, "persistence context");
  const request = snapshot(value, "persistence request") as Record<string, unknown>; const context = snapshot(contextValue, "persistence context") as Record<string, unknown>;
  const control = parseControlPlaneSnapshot(context.controlPlaneSnapshot); object(context.humanQaContext, "human QA context"); object(context.humanQaContext.caliperProvenanceContext, "caliper provenance context"); if (context.humanQaContext.caliperProvenanceContext.evaluatedAt !== control.observedAt) throw new TypeError("host clock snapshot must exactly match the JSC-0215 evaluation clock");
  object(request.humanQaRequest, "raw human QA request"); const rawHuman = request.humanQaRequest; object(rawHuman.caliperProvenanceRequest, "raw caliper request"); object(rawHuman.caliperProvenanceRequest.formalizationRequest, "raw formalization request");
  const candidate = parseFormalizationCandidate(rawHuman.caliperProvenanceRequest.formalizationRequest.candidate); const attestation = parseNonProxyHumanQaDecisionAttestation(rawHuman.decisionAttestation);
  const human = await evaluateNonProxyHumanQaDecision(rawHuman, context.humanQaContext);
  const expectedJob = { id: candidate.generation.jobId, canonicalInputSha256: candidate.generation.canonicalInputSha256, reviewHeadEventSha256: candidate.generation.reviewHeadEventSha256, generatorInputSha256: candidate.generation.generatorInputSha256, output: { manifestSha256: candidate.manifestSha256, modelSha256: candidate.modelSha256, manifestByteLength: candidate.manifestByteLength, modelByteLength: candidate.modelByteLength } };
  if (control.tenantId !== candidate.tenantId || control.frameModelId !== candidate.frameModelId || control.frameVariantId !== candidate.frameVariantId || !same(control.generationJob, expectedJob)) throw new TypeError("control-plane snapshot cannot relabel tenant, model, variant, job, head, input, or output");
  if (control.candidateAssetVersion.id !== candidate.id || control.candidateAssetVersion.version !== candidate.version) throw new TypeError("control-plane candidate AssetVersion identity must be exact and unused");
  if (control.measurementSet.sha256 !== candidate.requirements.physical.measurementSetSha256) throw new TypeError("control-plane MeasurementSet mapping does not match the verified decision");
  const mappedHashes = control.sourceMappings.map((item) => item.sourceAssetSha256); if (!same(mappedHashes, candidate.sourceAssetHashes)) throw new TypeError("control-plane source mapping must cover the exact verified source hash set without relabeling");
  const authority = control.reviewerAuthority; const trustedKeys = context.humanQaContext.reviewerTrust; object(trustedKeys, "reviewer trust"); object(trustedKeys.trustedKeys, "reviewer trust.trustedKeys"); const trusted = trustedKeys.trustedKeys[attestation.keyId]; object(trusted, "selected reviewer trust record");
  if (authority.authorityId !== attestation.authorityId || authority.keyId !== attestation.keyId || authority.reviewerId !== attestation.reviewerId || authority.publicKeyFingerprintSha256 !== attestation.publicKeyFingerprintSha256 || !same(authority.publicJwk, trusted.publicJwk)) throw new TypeError("control-plane reviewer authority snapshot does not match the independently verified reviewer identity and key");
  const fingerprint = await nonProxyHumanQaPublicJwkFingerprintSha256(authority.publicJwk); if (fingerprint !== authority.publicKeyFingerprintSha256) throw new TypeError("control-plane reviewer authority fingerprint does not match its exact public JWK");
  if (Date.parse(authority.createdAt) > Date.parse(attestation.reviewedAt) || Date.parse(authority.createdAt) > Date.parse(attestation.issuedAt) || Date.parse(authority.createdAt) > Date.parse(control.observedAt)) throw new TypeError("reviewer authority must exist before human review, signed issuance, and host observation");
  const reviewTrust = context.humanQaContext.reviewerTrust; object(reviewTrust, "reviewer trust"); const maximumReviewAgeMs = reviewTrust.maximumReviewAgeMs; reviewAge(maximumReviewAgeMs, "reviewer trust.maximumReviewAgeMs"); const reviewPolicySha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/review-policy/v1", maximumReviewAgeMs })); if (control.reviewPolicy.maximumReviewAgeMs !== maximumReviewAgeMs || control.reviewPolicy.sha256 !== reviewPolicySha256) throw new TypeError("host review-policy snapshot does not match the JSC-0215 trust policy");

  const reviewerAuthority = await row("jessica/non-proxy-qa/reviewer-authority-row/v1", "nqra", { tenantId: candidate.tenantId, authorityId: attestation.authorityId, keyId: attestation.keyId, reviewerId: attestation.reviewerId, scope: NON_PROXY_HUMAN_QA_SCOPE, algorithm: "ES256" as const, publicKeyFingerprintSha256: attestation.publicKeyFingerprintSha256, publicJwk: structuredClone(authority.publicJwk), status: "active" as const, createdAt: authority.createdAt, revokedAt: null }) as NonProxyQaReviewerAuthorityRow;
  const sourceSetSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/source-set/v1", sourceAssetSha256s: candidate.sourceAssetHashes }));
  let assetVersion: NonProxyAssetVersionRow | null = null;
  if (attestation.decision === "approve") { if (!human.approvedReviewProjection) throw new TypeError("approve persistence requires the internally verified JSC-0215 projection"); const projection = human.approvedReviewProjection; const assetBody = { tenantId: projection.tenantId, frameModelId: projection.frameModelId, frameVariantId: projection.frameVariantId, version: projection.version, generationJobId: projection.generation.jobId, quality: projection.quality, generationMethod: projection.generationMethod, modelUrl: projection.modelUrl, manifestUrl: projection.manifestUrl, manifestSha256: projection.manifestSha256, manifestByteLength: projection.manifestByteLength, modelSha256: projection.modelSha256, modelByteLength: projection.modelByteLength, sourceSetSha256, attachmentMatrix: [...projection.attachmentMatrix], qualityEnvelope: structuredClone(projection.qualityEnvelope), status: "approved" as const, fixtureStatus: "unverified" as const, reviewStatus: "approved" as const, admission: "internal-review-only" as const, promotable: false as const, rightsScope: "internal-review-only" as const, recommendedForLive: false as const, publicationEligible: false as const }; const assetRowSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/asset-version-row/v1", id: projection.id, body: assetBody })); assetVersion = { id: projection.id, rowSha256: assetRowSha256, ...assetBody } as NonProxyAssetVersionRow; }
  const reviewFreshUntil = new Date(Date.parse(attestation.reviewedAt) + maximumReviewAgeMs).toISOString(); if (human.validUntil !== new Date(Math.min(Date.parse(attestation.expiresAt), Date.parse(attestation.composition.inputValidUntil), Date.parse(reviewFreshUntil))).toISOString()) throw new TypeError("JSC-0215 validity does not match the host review policy horizon");
  const reviewBody = { tenantId: candidate.tenantId, frameModelId: candidate.frameModelId, frameVariantId: candidate.frameVariantId, candidateAssetVersionId: candidate.id, candidateVersion: candidate.version, generationJobId: candidate.generation.jobId, canonicalInputSha256: candidate.generation.canonicalInputSha256, reviewHeadEventSha256: candidate.generation.reviewHeadEventSha256, generatorInputSha256: candidate.generation.generatorInputSha256, output: structuredClone(attestation.output), sourceAssetSha256s: [...attestation.sourceAssetSha256s], sourceSetSha256, measurementSetId: control.measurementSet.id, measurementSetSha256: attestation.measurementSetSha256, specimenId: attestation.specimenId, composition: structuredClone(attestation.composition), decisionPayloadSha256: human.decisionPayloadSha256, signatureBase64: attestation.signatureBase64, reviewerAuthorityRowId: reviewerAuthority.id, reviewerAuthorityId: attestation.authorityId, reviewerKeyId: attestation.keyId, reviewerId: attestation.reviewerId, reviewerPublicKeyFingerprintSha256: attestation.publicKeyFingerprintSha256, decision: attestation.decision, issueCategories: [...attestation.issueCategories], notes: attestation.notes, approvedQualityEnvelope: attestation.approvedQualityEnvelope ? structuredClone(attestation.approvedQualityEnvelope) : null, reviewedAt: attestation.reviewedAt, issuedAt: attestation.issuedAt, expiresAt: attestation.expiresAt, inputValidUntil: attestation.composition.inputValidUntil, maximumReviewAgeMs, reviewFreshUntil, reviewPolicySha256, effectiveValidUntil: human.validUntil, approvedAssetVersionRowSha256: assetVersion?.rowSha256 ?? null, approvedAssetProjection: assetVersion ? structuredClone(assetVersion) : null, rightsScope: "internal-review-only" as const, terminal: true as const };
  const reviewSemanticSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/terminal-review-identity/v1", tenantId: candidate.tenantId, candidateAssetVersionId: candidate.id, candidateVersion: candidate.version, generationJobId: candidate.generation.jobId, decisionPayloadSha256: human.decisionPayloadSha256 })); const reviewRowSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/human-review-row/v1", body: reviewBody })); const reviewRecord = { id: `nqhr_${reviewSemanticSha256}`, rowSha256: reviewRowSha256, ...reviewBody } as NonProxyHumanQaRecordRow;

  let binding: NonProxyAssetVersionBindingRow | null = null; let sourceRows: NonProxyAssetVersionSourceRow[] = [];
  if (attestation.decision === "approve") {
    if (!human.approvedReviewProjection || !assetVersion) throw new TypeError("approve persistence requires the internally verified JSC-0215 projection"); const projection = human.approvedReviewProjection;
    binding = await row("jessica/non-proxy-qa/asset-binding-row/v1", "nqab", { tenantId: projection.tenantId, reviewRecordId: reviewRecord.id, assetVersionId: projection.id, frameModelId: projection.frameModelId, frameVariantId: projection.frameVariantId, generationJobId: projection.generation.jobId, sourceSetSha256, qualityEnvelope: structuredClone(projection.qualityEnvelope), decisionPayloadSha256: human.decisionPayloadSha256, effectiveValidUntil: human.validUntil, assetVersionRowSha256: assetVersion.rowSha256, rightsScope: "internal-review-only" as const, recommendedForLive: false as const, publicationEligible: false as const }) as NonProxyAssetVersionBindingRow;
    sourceRows = await Promise.all(control.sourceMappings.map(async (mapping) => row("jessica/non-proxy-qa/asset-source-row/v1", "nqas", { tenantId: projection.tenantId, assetVersionId: projection.id, frameModelId: projection.frameModelId, frameVariantId: projection.frameVariantId, sourceAssetId: mapping.sourceAssetId, sourceSha256: mapping.sourceAssetSha256 }) as Promise<NonProxyAssetVersionSourceRow>));
  }
  const expectedExisting = { reviewerAuthority: { id: reviewerAuthority.id, rowSha256: reviewerAuthority.rowSha256 }, reviewRecord: { id: reviewRecord.id, rowSha256: reviewRecord.rowSha256 }, assetVersion: assetVersion ? { id: assetVersion.id, rowSha256: assetVersion.rowSha256 } : null, binding: binding ? { id: binding.id, rowSha256: binding.rowSha256 } : null, sourceRows: sourceRows.map(({ id, rowSha256 }) => ({ id, rowSha256 })) };
  if (control.existingRows.reviewerAuthority !== null && !same(control.existingRows.reviewerAuthority, expectedExisting.reviewerAuthority)) throw new TypeError("deterministic persistence identity collision: existing reviewer authority has different canonical contents");
  const terminalAbsent = control.existingRows.reviewRecord === null && control.existingRows.assetVersion === null && control.existingRows.binding === null && control.existingRows.sourceRows.length === 0;
  if (!terminalAbsent && !same({ reviewRecord: control.existingRows.reviewRecord, assetVersion: control.existingRows.assetVersion, binding: control.existingRows.binding, sourceRows: control.existingRows.sourceRows }, { reviewRecord: expectedExisting.reviewRecord, assetVersion: expectedExisting.assetVersion, binding: expectedExisting.binding, sourceRows: expectedExisting.sourceRows })) throw new TypeError("deterministic persistence identity collision: existing terminal row identity has different canonical contents");
  const body = { schemaVersion: 1 as const, planType: "non-proxy-qa-persistence-row-projections" as const, decision: attestation.decision, reviewerAuthority, reviewRecord, assetVersion, binding, sourceRows, authority: DENIALS };
  const planSha256 = await sha256Hex(canonicalJson({ domain: "jessica/non-proxy-qa/persistence-plan/v1", body })); return inspectNonProxyQaPersistencePlanIntegrity(deepFreeze({ ...body, planSha256, idempotencyKey: `nqpp_${planSha256}` }));
}
